### ISSUE TITLE
qualifiedMaker - Makerskwalificatie komt niet door

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#1]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Voor Vervaardigers geven we nu rol, naam, plaats vervaardiging mee.
Daar ontbreekt nog de kwalificatie (tussen haakjes), zoals:
- 1. & 2. School van
- Vermeld op object
- Schrijver & uitgever (met 'óf'-relatie(!))
- 5. & 6. Toegeschreven aan

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/AK-MAK-1464-A
2. https://www.rijksmuseum.nl/nl/collectie/RP-P-1956-10
3. https://www.rijksmuseum.nl/nl/collectie/NG-595
4. https://www.rijksmuseum.nl/nl/collectie/BI-H-1928
5. http://hdl.handle.net/10934/RM0001.COLLECT.491269
6. https://www.rijksmuseum.nl/nl/collectie/BK-AM-33

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Kamerschermen-Vroege-lente--b83e44dd9feb44ddce48ab94cc616795
2. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/De-Bewening--6348161d8c2f11b3aa09a488677edd6c
3. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-Gaspard-de-Coligny--8cf4dcb8c4d2dd40b8152d6302eb2864?query=NG-595&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
4. https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--8f52d4bedd6922c99ed476599f1decc6?query=BI-H-1928&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
5. https://rijks-acc.q42labs.com/nl/collectie/object/Virginaal--842eb80d3bbd5ccba0b53fd73279e963?query=BK-KOG-595&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
7. https://rijks-acc.q42labs.com/nl/collectie/object/Pleurants-van-het-praalgraf-van-Isabella-van-Bourbon--27fb4e181730d2f0839af30882e32952?tab=data

---

**Comment by jorisbr** [comment]
De oorzaak ligt in bij integration layer: https://github.com/Rijksmuseum/pattern_book/issues/427.

**Comment by edwardanderson** [comment]
I just noticed the referral to this issue from the Pattern Book. We do provide "school of" qualifications in line with [implementing_maker.md#group](https://github.com/Rijksmuseum/pattern_book/blob/main/docs/design/implementing_maker.md#group).

The classification qualifying the assertion that the production was carried out by a _school_ is here: https://github.com/Rijksmuseum/pattern_book/blob/main/pattern_book/examples/access/Collection/cidoc_crm/linked_art/HumanMadeObject/parts/production/maker/qualifier/group/school_of/200106707.ttl.

Looking at AK-MAK-1464-A. this specific object does not appear to be affected by the linked issue:

```turtle
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

<https://id.rijksmuseum.nl/20055620>
    a crm:E22_Human-Made_Object ;
    crm:P108i_was_produced_by
        [
            a crm:E12_Production ;
            crm:P9_consists_of
                [
                    a crm:E12_Production ;
                    crm:P141i_was_assigned_by
                        [
                            a crm:E13_Attribute_Assignment ;
                            crm:P141_assigned
                                [
                                    a crm:E74_Group ;
                                    crm:P2_has_type <http://vocab.getty.edu/aat/300266106> ;
                                    crm:P95i_was_formed_by
                                        [
                                            a crm:E66_Formation ;
                                            crm:P15_was_influenced_by <https://id.rijksmuseum.nl/21052635> ;
                                        ] ;
                                ] ;
                            crm:P177_assigned_property_of_type crm:P14_carried_out_by ;
                            crm:P2_has_type <http://vocab.getty.edu/aat/300404284> ;
                        ] ;
                    crm:P1_is_identified_by
                        [
                            a crm:E42_Identifier ;
                            crm:P190_has_symbolic_content "1" ;
                            crm:P2_has_type <http://vocab.getty.edu/aat/300451544> ;
                        ] ;
                    crm:P2_has_type <http://vocab.getty.edu/aat/300404450> ;
                    crm:P32_used_general_technique <https://id.rijksmuseum.nl/2202217> ;
                    crm:P7_took_place_at <https://id.rijksmuseum.nl/23027> ;
                ] ;
        ] ;
.
```

**Comment by jorisbr** [comment]
Good catch! This is an alternate pattern that I need to include in the query I created.

**Comment by verwinv** [comment]
@jorisbr Deze heb ik uitgebreid met voorbeelden uit de metadatareview

**Comment by verwinv** [comment]
gerelateerd aan https://github.com/Rijksmuseum/pattern_book/issues/467
en https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/issues/43
