### ISSUE TITLE
Beschrijving - Wens om beschrijving óók te tonen

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#108]
Gemeld door @BasRijks, Marte Sophie, Jan van Campen, Menno Fitski, Peter

De wens is dat:

- we op de **Over-tab** (zoals het nu werkt) de Etikettekst tonen indien beschikbaar, anders de beschrijving 
- we op de **Gegevens-tab** _nooit_ de Etikettekst tonen, _altijd_ enkel de Beschrijving

# Beschrijving
URL(s) van de pagina(’s) waarop je dit ziet:
[https://www.rijksmuseum.nl/nl/collectie/object/Pax-met-het-sterfbed-en-de-hemelvaart-van-Maria--2ab6d231eb5dbe59a32bf937a93785ce?collectionSearchContext=Art&page=1&sortingType=Popularity&facets[0].id=ff2788d57ce1f536e53c6357bb581f8a&tab=data](https://www.rijksmuseum.nl/nl/collectie/object/Pax-met-het-sterfbed-en-de-hemelvaart-van-Maria--2ab6d231eb5dbe59a32bf937a93785ce?collectionSearchContext=Art&page=1&sortingType=Popularity&facets%5b0%5d.id=ff2788d57ce1f536e53c6357bb581f8a&tab=data)
# Pagina of Tab waarop je dit ziet:
Bekijk alle gegevens
# Veld & sub-veld waarop je dit ziet:
Beschrijving
# Beschrijf wat er mis gaat:
Als ik het goed zie wordt hier de etikettekst getoond, en wanneer er geen etikettekst is wordt de objectbeschrijving uit Adlib getoond. Ik denk dat het belangrijk is om ook de objectbeschrijving op de objectpagina te tonen. In de eerste plaats omdat de beschrijving de foto verduidelijkt, ten tweede omdat de beschrijving woorden bevat waarop gezocht kan worden. 
# Heb je ook een screenshot? Voeg deze dan graag toe
![Picture 15](https://github.com/user-attachments/assets/c8fa3c73-d735-4dc8-b060-40adfa368d01)

**Comment by verwinv** [comment]
Wens volgens Peter:
- Over-tab: Etikettekst tonen indien beschikbaar, anders de beschrijving
- Gegevens-tab: nooit de Etikettekst tonen, altijd enkel de Beschrijving

**Comment by DannyGJdeJong** [comment]
Gaan we oppakken
