### ISSUE TITLE
[Preferred Title] - [Soms is er geen titel beschikbaar]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#11]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Bekijk bijvoorbeeld dit object:
```
<elementId>: 4:51460f17-1b31-4eff-b333-c6e2a77f2194:390957
<id>: 390957
hasImage: true
inMuseum: false
nodeId: 1deb20c8dedb5e6693bd53c9dc1f48eb
objectNumber: RP-P-OB-201.575
popularityScore: 29
uri: https://id.rijksmuseum.nl/200569851
```
Uit de Sparql query blijkt dat er een titel beschikbaar is maar die komt niet in de node en niet in elastic door.

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2.

---

**Comment by jorisbr** [comment]
relates to https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/issues/5

**Comment by verwinv** [comment]
Relates to https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/issues/44
