### ISSUE TITLE
Vervaardiging (op datatab) - Vervaardiger komt dubbel door

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#12]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Onder 'vervaardiging' staat nu dubbele info:

```Vervaardiging

schilder: Rembrandt van Rijn, Amsterdam

**Rembrandt van Rijn**
```

Die tweede vermelding is dubbelop.

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Stilleven-met-bloemen-op-een-marmeren-tafelblad--570d1419506e38cb3916f640fe5a2328?query=europa&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Portret-van-Oopjen-Coppit--6b7d967cdf05b81c2416359e06adaf52?collectionDomain=Art&page=1&sortingType=Popularity&tab=data

---
## Screenshots

1. ![Screenshot 2024-06-27 at 15 09 06](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/734a0adf-e8e4-44e5-a86b-59abc345d5cb)
2. ![Screenshot 2024-06-27 at 15 08 46](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/56f2f3b9-e3da-4988-a010-0e019c0c62e4)

**Comment by jorisbr** [comment]
Dit komt niet langer voor
