### ISSUE TITLE
Amsterdam node doesn't work for library

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#13]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/zoeken?collectionDomain=Library&page=1&sortingType=Default&facets[0].id=e6a8a875b6aa0e65ab67c31783ebc635
2.

---

**Comment by jorisbr** [comment]
The query appears to be working and thus this is suspected to get resolved with a next run

**Comment by DannyGJdeJong** [comment]
This is resolved now
