### ISSUE TITLE
Vervaardiging - Plaats ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#17]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

'Gemaakt in' staat wel bij de 'Zoek verder op'-nodes, maar ontbreekt in het bovenste deel

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/RP-P-1903-A-23648
2.

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Gezicht-op-de-Montelbaanstoren-te-Amsterdam--1a563472309b3fe2822e7524f7aade29?query=musculus&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2.

---
## Screenshots

![image (1)](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/1b6a9deb-2b1d-413b-ac2e-972b70a6946a)

**Comment by jorisbr** [comment]
Deze moeten we volgens mij even bespreken. Als ik er zo naar kijk heb ik het idee dat de data klopt namelijk. Er zijn 2 productie plaatsen:
- Amsterdam (aldaar uitgegeven door Pierre Fouqet)
- Parijs (eveneens daar uitgegeven ditmaal door Francois Basan)
De plaatsen noord-holland en ile-de-france zijn bovenliggende plaatsen die naar voren komen uit de hierarchie.

**Comment by verwinv** [comment]
Dit is zoals ontworpen!
