### ISSUE TITLE
Vervaardiging - Vervaardigers ontbreken

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#18]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. [RP-P-1903-A-23648](https://www.rijksmuseum.nl/nl/collectie/RP-P-1903-A-23648): Prentmaker P. Duret staat wel vermeld in Rijksstudio, niet in Collectie online
2. [BK-17496](https://www.rijksmuseum.nl/nl/collectie/BK-17496): 'porseleinfabriek: Meissener Porzellan Manufaktur' en '   ontwerper: Johann Gottlieb Kirchner (verworpen toeschrijving)' komen niet door
3. ...meer voorbeelden in [de metadatareviewsheet](https://docs.google.com/spreadsheets/d/1PF9wVdmPcj9lSuNFtFbC-yhSpprJnIN-a94gRdvhNy8/edit?gid=187235003#gid=187235003)

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/RP-P-1903-A-23648
2. https://www.rijksmuseum.nl/nl/collectie/BK-17496

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Gezicht-op-de-Montelbaanstoren-te-Amsterdam--1a563472309b3fe2822e7524f7aade29?query=musculus&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Blauwe-ara--b3c64fbd259c122cdf8fa9e9a32246c2?query=BK-17496&collectionDomain=Art&page=1&sortingType=Popularity&tab=data

---
## Screenshots
<img width="1280" alt="Screenshot 2024-07-05 at 12 40 06" src="https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/05bce0ac-5e80-41ea-84a4-6fe1ad41e1f8">
![Screenshot 2024-07-08 at 13 29 29](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/f3c0f1d4-051d-42d2-857e-aa20003f0612)

**Comment by jorisbr** [comment]
There appears to be no maker associated with the 5th sub production event. This seems to be a bug in the integration layer for which an issue was already created: https://github.com/Rijksmuseum/pattern_book/issues/427

**Comment by DannyGJdeJong** [comment]
Komt nu allemaal goed door!
