### ISSUE TITLE
Node - Ontbreekt in 'Gegenereerde Nodepagina Overzicht'

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#19]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

[ Rozenburg, N.V. Haagsche Plateelfabriek](https://rijks-acc.q42labs.com/nl/collectie/zoeken?collectionDomain=Art&page=1&sortingType=Popularity&facets[0].id=5fc5623d819e754c5443b2d2cce37e6f) is een node, dus zou ook in het [Gegenereerde pagina-overzicht](https://rijks-acc-qcms.azurewebsites.net/generatedNodePageItems?query=Rozenburg&page=1) moeten terugkomen.

## Relevant examples

Rijksstudio links: NVT

Collectie Online links: zie boven in lopende tekst

---
## Screenshots

![Screenshot 2024-07-08 at 11 49 12](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/a29db7ec-548d-40b1-8944-05a00dd6fe99)

**Comment by DannyGJdeJong** [comment]
![image](https://github.com/user-attachments/assets/b57eac4a-94cf-461b-9071-822f124fb187)

Seems to be resolved now
