### ISSUE TITLE
Maker - Jesus Christ is an organisation

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#2]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

De node 'Jezus Christus' wordt gelabeled als organisatie.
Dat mag een (historisch) persoon worden.

## Relevant examples

https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/node/Jezus-Christus--0c8069942f1c311e1a1e6e7a0b29023d?collectionDomain=Art&page=1&sortingType=Popularity&facets[0].id=0c8069942f1c311e1a1e6e7a0b29023d

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/rijksstudio/onderwerpen/jezus-christus
2.

Collectie Online links:

1.
2.

---
## Screenshots

![Screenshot 2024-06-11 at 20 50 22](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/3706db9f-f794-4734-b571-c2dbf1e781a7)

**Comment by jorisbr** [comment]
Dit kunnen we bekijken als we de personen op gaan splitsen in historische personen en makers. Mijn verwachting is dat dit niet te fiksen valt. We kunnen immers niet betrouwbaar zeggen welke organisatie eigenlijk een persoon is.

**Comment by verwinv** [comment]
Mail Coen.

**Comment by verwinv** [comment]
[20 aug] Edward heeft Jezus gefixt in Adlib
