### ISSUE TITLE
Documentatie - Enkel ongelinkte documentatie wordt getoond

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#21]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Onder de sectie 'Documentatie' komen enkel de publicaties zonder link door.

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BK-17496
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Blauwe-ara--b3c64fbd259c122cdf8fa9e9a32246c2?tab=data
2.

---
## Screenshots

![Screenshot 2024-07-08 at 13 38 09](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/8f9fc309-a492-43d6-aa14-344c1c9b6821)

**Comment by DannyGJdeJong** [comment]
Deels een patternbook issue: https://github.com/Rijksmuseum/pattern_book/issues/428

Deels aan onze kant een issue: `?libraryObject rdf:type bib:Instance.` bestaat vaak niet meer en moeten we dus uit de query halen.
