### ISSUE TITLE
Over-tab - Afmetingen & Fysieke kenmerken ontbreken

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#22]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Op de over-tab ontbreken de velden **Afmetingen** & **Fysieke kenmerken**.
Zie screenshot vgl. Figma.

## Relevant examples

Rijksstudio links:

1. 
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Blauwe-ara--b3c64fbd259c122cdf8fa9e9a32246c2?tab=data
2.

---
## Screenshots
![Screenshot_08_07_2024__13_46](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/68d8a60e-0ed5-4fe7-a644-529a89064106)

**Comment by DannyGJdeJong** [comment]
Dit is geen sparqlbook issue, de data is er gewoon. Ik heb er een Jira ticket voor aangemaakt: https://rijksmuseum.atlassian.net/browse/CO-1700?atlOrigin=eyJpIjoiZTI5ZDRkNWYzYzZhNGJmOWIzZTgxM2VjOTQ2OTM0ZGUiLCJwIjoiaiJ9
