### ISSUE TITLE
Catalogusreferentie - Ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#23]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Het veld 'catalogusreferentie' (niet te verwarren met de bestandscatalogus!) ontbreekt nog.
Deze is vooral voor de prenten van groot belang.

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/RP-P-1957-377
2. https://www.rijksmuseum.nl/nl/collectie/RP-P-1943-725
3. https://www.rijksmuseum.nl/nl/collectie/RP-P-1908-2595

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Zelfportret-met-pet-van-voren-alleen-het-hoofd--9c9292bf94b923ba5f275ddd4487e7e4?query=RP-P-1957-377&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-Cornelis-de-Witt--0b06369b5dd8e42bd786d70fd1c2336e?&tab=data
3. https://rijks-acc.q42labs.com/nl/collectie/object/Schaatswedstrijd-te-Harlingen-1829--23d21b3845935655b0de0d214699f6ad?&tab=data

---
## Screenshots
![Screenshot 2024-07-08 at 15 07 28](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/941eb831-a551-4012-bf25-5b37fec941d1)

![Portret_van_Cornelis_de_Witt__William_Baillie__naar_Caspar_Netscher__1774_-_Rijksmuseum_and_Portret_van_Cornelis_de_Witt_-_Rijksmuseum](https://github.com/user-attachments/assets/4b51ea82-b984-4be3-8538-360bed98d1aa)

![Schaatswedstrijd_te_Harlingen__1829__anoniem__naar_S__en_J__de_Jong__1829_-_Rijksmuseum_and_Schaatswedstrijd_te_Harlingen__1829_-_Rijksmuseum](https://github.com/user-attachments/assets/d1665c61-6d63-404d-aa12-e6a65d5f4126)

**Comment by DannyGJdeJong** [comment]
Created a patternbook issue: https://github.com/Rijksmuseum/pattern_book/issues/511

**Comment by verwinv** [comment]
@DannyGJdeJong Check if available

**Comment by DannyGJdeJong** [comment]
Ik krijg nu niet de catalogusreferentie terug die ik zou verwachten.

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>

SELECT ?catalogueEntry ?text
WHERE {
    ?objectUri rdf:type crm:E22_Human-Made_Object.
    ?objectUri crm:P67i_is_referred_to_by ?catalogueEntry.
    ?objectUri rdf:type crm:E22_Human-Made_Object.
    ?objectUri crm:P1_is_identified_by ?identifier.
    ?identifier crm:P190_has_symbolic_content ?idText.

    FILTER(?idText = "RP-P-1943-725")

    ?catalogueEntry crm:P190_has_symbolic_content ?text.
}
```

Geeft

| catalogueEntry  | text                                             |
|-----------------|--------------------------------------------------|
| _:node206501376 | "verzamelaarsmerk, verso, gestempeld: Lugt 2228" |
| _:node206501378 | ": Lugt 2228"                                    |

Dit krijg ik totaal niet terug te zien op Rijksstudio. https://www.rijksmuseum.nl/nl/collectie/RP-P-1943-725

De data `Hollstein Dutch 4` is wel terug te vinden in de context van het object in de access store, maar heeft wel een nieuwe query nodig om deze goed te kunnen queryen. Klopt het dat dit anders is dan de `hasCatalogue` property?

**Comment by verwinv** [comment]
Is beschikbaar in Access model, moet anders gequeried worden.

**Comment by DannyGJdeJong** [comment]
Aantal dingen over de catalogusreferentie:

De catalogusreferentie kan een van 3 dingen zijn (non-exhaustive):
- Bovengenoemde voorbeeld (Hollstein Dutch, etc) 
- Een link naar [kb.nl](http://resolver.kb.nl/resolve?urn=KBNRC01:000030493:mpeg21:p008) in het geval van bijvoorbeeld https://www.rijksmuseum.nl/nl/collectie/NG-2011-18-36-27. Rijksstudio laat deze data volledig weg.
- Zowel een catalogusreferentie als hierboven beschreven (`FMH 3982-F`) + een notitie hierover (Frederik Muller, De Nederlandsche geschiedenis in platen : beredeneerde beschrijving van Nederlandsche historieplaten, zinneprenten en historische kaarten, 4 delen, F. Muller, Amsterdam 1863-1882, dl. II (jaren 1702 tot 1795), p. 181, nr. 3982/F.). In Rijksstudio wordt deze notitie onder documentatie geschaald, maar in de access store kunnen we hier geen verschil tussen zien anders dan dat er geen catalogus onder hangt via een `crm:P2_has_type` relatie. https://www.rijksmuseum.nl/nl/collectie/RP-P-OB-207.005

Welke dingen willen we nu wel of niet laten zien?

Query ter illustratie (als je de optional weghaalt returnen we dus alleen de dingen uit het originele voorbeeld):
```
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?objectUri ?objectId ?propertyUri ?propertyId ?nlValue ?enValue
WHERE {
    {
        SELECT ?objectUri ?catalogueReference
        WHERE {
            ?objectUri rdf:type crm:E22_Human-Made_Object.
            ?objectUri crm:P141i_was_assigned_by ?catalogueReference.
            # references
            ?catalogueReference crm:P2_has_type <http://vocab.getty.edu/aat/300311954>.
        }
        ORDER BY ?objectUri
        LIMIT 50000
        OFFSET 0
    }

    ?catalogueReference crm:P141_assigned ?linguisticObject.

    OPTIONAL {
        ?catalogueReference crm:P2_has_type ?propertyUri.
        # references
        FILTER(?propertyUri != <http://vocab.getty.edu/aat/300311954>)
    }

    ?linguisticObject rdf:type crm:E33_Linguistic_Object.
    ?linguisticObject crm:P1_is_identified_by ?identifier.

    ?identifier rdf:type crm:E42_Identifier.
    ?identifier crm:P190_has_symbolic_content ?value.


    BIND(MD5(STR(?objectUri)) AS ?objectId)
    BIND(MD5(STR(?propertyUri)) AS ?propertyId)
    BIND(?value AS ?nlValue)
    BIND(?value AS ?enValue)
}
```

**Comment by DannyGJdeJong** [comment]
Het simpelste zou zijn om de catalogusreferentie, de url en de notities exact hetzelfde te behandelen. Dan zouden we die drie dingen dus gemixt in het catalogusreferentieveld hebben.

**Comment by DannyGJdeJong** [comment]
De catalogusreferentie komt met de huidige implementatie van de catalogueReference property correct door.

We negeren de URLs naar de catalogi en de notities ervan komen nu in het descriptiveNote veld terecht.

**Comment by DannyGJdeJong** [comment]
Voor de tweede link komt de tweede catalogusreferentie alleen door onder het documentatieveld:

![Image](https://github.com/user-attachments/assets/ee715e0e-8540-4046-951b-859169e605a2)
