### ISSUE TITLE
Onderdeel van - Waarde ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#24]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. BK-NM-1010: Van de 4 aanwezige onderdelen in Rijksstudio zijn er in Collectie Online 3 aanwezig
2. BK-AM-33: 10 onderdelen, en daarmee de hele sectie, ontbreken
3. Relaties (is deel van) ontbreekt bij NG-1983-62-42, bijvoorbeeld. 
4. Onderdelen A - J

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BK-NM-1010
2. https://www.rijksmuseum.nl/nl/collectie/BK-AM-33
3. https://www.rijksmuseum.nl/nl/collectie/RP-F-2019-242-15-2
4. https://www.rijksmuseum.nl/nl/collectie/BK-AM-33
5. ...meer voorbeelden [in de metadatareviewsheet](https://docs.google.com/spreadsheets/d/1PF9wVdmPcj9lSuNFtFbC-yhSpprJnIN-a94gRdvhNy8/edit?gid=187235003#gid=187235003)

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Poppenhuis-van-Petronella-Oortman--62700ab4ff22218345de76f77d58ad39
2. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Pleurants-van-het-praalgraf-van-Isabella-van-Bourbon--27fb4e181730d2f0839af30882e32952?&tab=data
3. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-een-onbekend-jong-stel-in-Kobe--96fa35765304782f0b7e06aa3897afbf?&tab=data
4. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Pleurants-van-het-praalgraf-van-Isabella-van-Bourbon--27fb4e181730d2f0839af30882e32952?&tab=data

---
## Screenshots
![Screenshot 2024-07-08 at 15 19 50](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/e4251542-1d68-427b-8a58-811ddec88aec)

![Pleurants_van_het_praalgraf_van_Isabella_van_Bourbon_-_Rijksmuseum_and_Pleurants_van_het_praalgraf_van_Isabella_van_Bourbon__Borman_werkplaats__toegeschreven_aan___Renier_van_Thienen__I___toegeschreven_aan___ca__1475_-_ca__1476_-_Rijksmuseu](https://github.com/user-attachments/assets/b33a64ca-dc5b-4117-871e-558109d48eda)

**Comment by DannyGJdeJong** [comment]
Hier missen heel wat `forms_part_of` relaties. Ik heb er een patternbook issue voor aangemaakt: https://github.com/Rijksmuseum/pattern_book/issues/512

**Comment by verwinv** [comment]
@DannyGJdeJong Check if available

**Comment by DannyGJdeJong** [comment]
These are available now and should show up after a new pipeline run.

**Comment by DannyGJdeJong** [comment]
Wederom terug van weggeweest, komt nu goed door op acceptatie en productie!
