### ISSUE TITLE
Datering - 'ca.' ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#25]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

De datering op Rijksstudio is met 'ca.'; de datering op Collectie Online is dat niet.

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BK-NM-1010
2. https://www.rijksmuseum.nl/collectie/AK-MAK-187
3. https://www.rijksmuseum.nl/nl/collectie/BK-AM-33

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Poppenhuis-van-Petronella-Oortman--62700ab4ff22218345de76f77d58ad39
2. https://rijks-acc.q42labs.com/nl/collectie/object/Shiva-Nataraja--95977e9e42c08b342dd8614230e2c948?query=AK-MAK-187
3. https://rijks-acc.q42labs.com/nl/collectie/object/Pleurants-van-het-praalgraf-van-Isabella-van-Bourbon--27fb4e181730d2f0839af30882e32952?tab=data

---
## Screenshots
![Screenshot 2024-07-08 at 15 43 52](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/8972a1ec-fa5c-474d-853e-041844bf0cdd)

**Comment by DannyGJdeJong** [comment]
Deze data mist ook in de access store. Ik heb er een patternbook issue voor aangemaakt: https://github.com/Rijksmuseum/pattern_book/issues/513

**Comment by DannyGJdeJong** [comment]
De data is nu in het Engels en Nederlands beschikbaar in de access store.

Voor bijvoorbeeld https://www.rijksmuseum.nl/nl/collectie/BK-NM-1010 is de Engelse waarde `c. 1686 - c. 1710` en de Nederlandse waarde `ca. 1686 - c. 1710`. Ik heb al naar Edward teruggekoppeld dat de Nederlandse waarde dus niet altijd klopt, maar we kunnen het in ieder geval alvast oppakken om de verschillende talen te returnen.

**Comment by DannyGJdeJong** [comment]
https://github.com/Rijksmuseum/pattern_book/issues/513 is nu closed.

> So this data will eventually be correct ...

In ieder geval niets dat we aan onze kant meer hoeven te doen.

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/f574ee47-6849-44fe-b124-f4e7918ed510)

Komt nu correct door op acc!
