### ISSUE TITLE
Opschriften / Merken - onderdelen 'methode', 'status' & 'positie' ontbreken

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#26]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. Adlibveld ‘Opschrift Methode’ ontbreekt; daar zou bij dit object 2x “handgeschreven” en 1x “geplakt“ moeten staan (op de oude website is dit wél correct).
2. De 'status' van het opschrift wordt niet getoond. In dit geval 'vals'
3. Adlibveld 'Opschrift positie' ontbreekt; daar zou bij dit object 1x ”recto eerste schutblad”, 1x “recto titelpagina“ en 1x “recto laatste schutblad” moeten staan.

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BI-H-1928
2. https://www.rijksmuseum.nl/nl/collectie/SK-A-4239
3. https://www.rijksmuseum.nl/nl/collectie/BI-H-1928
4. https://www.rijksmuseum.nl/nl/collectie/RP-P-2009-1217 
5. https://www.rijksmuseum.nl/nl/collectie/BK-NM-7474

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--8f52d4bedd6922c99ed476599f1decc6
2. https://rijks-acc.q42labs.com/nl/collectie/object/De-voetwassing--bb2c4c472cb533310ce5442dcfd85f70
3. https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--8f52d4bedd6922c99ed476599f1decc6 
4. https://rijks-acc.q42labs.com/nl/collectie/object/Marie-Antoinette-de-modekoningin-Gallerie-des-Modes-et-Costumes-Francais--2ec706ed1b819c793a9bd568b0a0b767?&tab=data
5. https://rijks-acc.q42labs.com/nl/collectie/object/Bekken--6f8b29fe1fd454ab8fb8e7546a53f632?tab=data

---

## Screenshots

Methode:
![Jours_de_solitude__Octave_Pirmez__1869_-_Rijksmuseum_and_Missing_Title_-_Rijksmuseum](https://github.com/user-attachments/assets/34589425-b08a-4538-81f7-ee1588a0ffe1)

Status:
![De_voetwassing_-_Rijksmuseum_and_De_voetwassing__Han_van_Meegeren__1935_-_1943_-_Rijksmuseum](https://github.com/user-attachments/assets/0fe97fd8-2d8b-4675-8476-7538ee4ce7ce)

Positie:
![Jours_de_solitude__Octave_Pirmez__1869_-_Rijksmuseum_and_Missing_Title_-_Rijksmuseum](https://github.com/user-attachments/assets/48324144-a1eb-49c9-bade-14ab6d25aa85)

**Comment by DannyGJdeJong** [comment]
Patternbook issue voor aangemaakt: https://github.com/Rijksmuseum/pattern_book/issues/514

**Comment by DannyGJdeJong** [comment]
Patternbook issue voor aangemaakt: https://github.com/Rijksmuseum/pattern_book/issues/514

**Comment by DannyGJdeJong** [comment]
Patternbook issue voor aangemaakt: https://github.com/Rijksmuseum/pattern_book/issues/514

**Comment by verwinv** [comment]
@jorisbr Check if available

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/55a77255-2c23-4b88-aeee-e1d66679f570)

Komt nu correct terug op acc!
