### ISSUE TITLE
Opschriften / Merken - Ontbreken

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#27]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Bij deze werken ontbreekt de property Opschriften / Merken:
- RP-P-1957-377: Beide opschriften ontbreken
- BK-NM-7474: Tweede opschrift ontbreekt 
- RP-P-1943-725: Eén opschrift ontbreekt
- RP-P-1908-2595: idem.
- RP-T-1931-284: idem.

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/RP-P-1957-377
2. https://www.rijksmuseum.nl/nl/collectie/BK-NM-7474
3. https://www.rijksmuseum.nl/nl/collectie/RP-P-1943-725
4. https://www.rijksmuseum.nl/nl/collectie/RP-P-1908-2595
5. https://www.rijksmuseum.nl/nl/collectie/RP-T-1931-284

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Zelfportret-met-pet-van-voren-alleen-het-hoofd--9c9292bf94b923ba5f275ddd4487e7e4?tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Bekken--6f8b29fe1fd454ab8fb8e7546a53f632?tab=data
3. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-Cornelis-de-Witt--0b06369b5dd8e42bd786d70fd1c2336e?&tab=data
4. https://rijks-acc.q42labs.com/nl/collectie/object/Schaatswedstrijd-te-Harlingen-1829--23d21b3845935655b0de0d214699f6ad?&tab=data
5. https://rijks-acc.q42labs.com/nl/collectie/object/Heuvellandschap--f925e0c20f9924602616f7c016834b2c?&tab=data

---
## Screenshots

![Zelfportret_met_pet__van_voren__alleen_het_hoofd_-_Rijksmuseum_and_Zelfportret_met_pet__van_voren__alleen_het_hoofd__Ignace-Joseph_de_Claussin__naar_Rembrandt_van_Rijn__1805_-_1844_-_Rijksmuseum](https://github.com/user-attachments/assets/a8c7997c-1171-4c73-985a-f1a447c1809c)

![Bekken__anoniem__ca__1322_-_ca__1350_-_Rijksmuseum_and_Bekken_-_Rijksmuseum](https://github.com/user-attachments/assets/59e0b794-e428-4eb9-8223-c096edb74cb8)

![Portret_van_Cornelis_de_Witt__William_Baillie__naar_Caspar_Netscher__1774_-_Rijksmuseum_and_Portret_van_Cornelis_de_Witt_-_Rijksmuseum](https://github.com/user-attachments/assets/1439c1db-faa5-4ba2-8144-12baa766d2e6)

![Schaatswedstrijd_te_Harlingen__1829__anoniem__naar_S__en_J__de_Jong__1829_-_Rijksmuseum_and_Schaatswedstrijd_te_Harlingen__1829_-_Rijksmuseum](https://github.com/user-attachments/assets/2f393819-8c0b-4639-

![Heuvellandschap__Carl_C__van_Niekerk__1931_-_Rijksmuseum_and_Heuvellandschap_-_Rijksmuseum](https://github.com/user-attachments/assets/cfb3a4f0-54f8-4c93-8e81-cf40399ad032)
a5ba-76dcd4621a72)

**Comment by DannyGJdeJong** [comment]
Patternbook issue voor aangemaakt: https://github.com/Rijksmuseum/pattern_book/issues/515

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/d56c0516-fa44-4414-bf10-500a05f88fbf)

Komt nu correct terug op acc!
