### ISSUE TITLE
Objecttype - Ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#28]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Het veld 'objecttype' is afwezig in Collectie Online

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/RP-T-1931-284
2. https://www.rijksmuseum.nl/nl/collectie/RP-P-2002-584

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Heuvellandschap--f925e0c20f9924602616f7c016834b2c?&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Doctor-Syntax-kijkt-naar-een-voorstelling-in-Covent-Garden-Theatre--d5f604b3ac8c524bc462537415c2481d?&tab=data

---
## Screenshots

![Heuvellandschap__Carl_C__van_Niekerk__1931_-_Rijksmuseum_and_Heuvellandschap_-_Rijksmuseum](https://github.com/user-attachments/assets/1673d575-d5b1-412a-aac2-c8cc887277d2)

**Comment by DannyGJdeJong** [comment]
Ik kan hier zo snel niks over vinden in de data @jorisbr kan jij dit bevestigen en een patternbook issue aanmaken?

**Comment by jorisbr** [comment]
Dit lijkt een fout te zijn bij het draaien van de pipeline. Zou met de volgende pipeline run goed moeten komen

**Comment by DannyGJdeJong** [comment]
Komt nog steeds niet door

**Comment by DannyGJdeJong** [comment]
Komt nu door dankzij de goede vondst van Joris 🥳
