### ISSUE TITLE
DescriptiveNote - Section shows ISBN instead of Title notes

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#3]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Incorrect content:
| ISBN/ISSN | 9781032271217, 9781003291473, 1032207833, 1032271213, 9781032207834 |

Expected content:
| Title Notes | Includes bibliographical references and index. |

## Relevant examples

Koha links:

1. https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=330406
2. https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=330179
3. https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=328062 (screenshot)

Collectie Online links:

1. {not found}
2. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/publicatie/Woodcuts-as-reading-guides-how-images-shaped-knowledge-transmission-in-medical-astrological-books-in-Dutch-1500-1550--31dad8becba0ab9b037091841c716745?query=Woodcuts+as+reading+guides&collectionDomain=Library&page=1&sortingType=Default
3. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/publicatie/Chakshudana-or-opening-the-eyes-seeing-South-Asian-art-anew--2871a35ddab29f55fb339a28891545d9?query=Chakshudana+or+opening+the+eyes&collectionDomain=Library&page=1&sortingType=Default

---
## Screenshots

<img width="731" alt="Screenshot 2024-06-12 at 20 36 05" src="https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/ef8d0ca7-f9ea-4edb-a689-bb2b55787f13">

**Comment by jorisbr** [comment]
Addressed [here](https://rijksmuseum.atlassian.net/browse/CO-1418)

**Comment by jorisbr** [comment]
Fixed
