### ISSUE TITLE
qualifiedMaker - ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#30]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

BK-AM-33:
- gieter: Renier van (I) Thienen, Brussel (stad) =  (toegeschreven aan)
- beeldhouwer: Borman werkplaats =  (toegeschreven aan)

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BK-AM-33
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Pleurants-van-het-praalgraf-van-Isabella-van-Bourbon--27fb4e181730d2f0839af30882e32952?&tab=data
2.

---
## Screenshots

![Pleurants_van_het_praalgraf_van_Isabella_van_Bourbon__Borman_werkplaats__toegeschreven_aan___Renier_van_Thienen__I___toegeschreven_aan___ca__1475_-_ca__1476_-_Rijksmuseum_and_Pleurants_van_het_praalgraf_van_Isabella_van_Bourbon_-_Rijksmuseu](https://github.com/user-attachments/assets/b49f2491-027b-4bd7-ab86-fc128aeead24)

**Comment by verwinv** [comment]
Duplicate of #1

**Comment by DannyGJdeJong** [comment]
Wordt meegenomen in de presenting lines, zie https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook/pull/208#pullrequestreview-2407312670

**Comment by DannyGJdeJong** [comment]
Is hier eigenlijk een pattern book issue van?

**Comment by DannyGJdeJong** [comment]
Komt nu goed door met de partProductionPresentingLines!
