### ISSUE TITLE
qualifiedMaker - Dubbele nodes in 'zoek verder op'

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#31]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- Borman werkplaats staat onder 'zoek verder op' als node 'Gemaakt door', niet 'Toegeschreven aan'
- Renier van Thienen (I)  staat onder 'zoek verder op' zowel als node 'Gemaakt door', en als 'Toegeschreven aan'
- Beide zouden zowel de 'Toegeschreven aan' als 'Gemaakt door'-noderelatie moeten hebben

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BK-AM-33
2.

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Pleurants-van-het-praalgraf-van-Isabella-van-Bourbon--27fb4e181730d2f0839af30882e32952?&tab=data
2.

---
## Screenshots

![Pleurants_van_het_praalgraf_van_Isabella_van_Bourbon__Borman_werkplaats__toegeschreven_aan___Renier_van_Thienen__I___toegeschreven_aan___ca__1475_-_ca__1476_-_Rijksmuseum_and_Pleurants_van_het_praalgraf_van_Isabella_van_Bourbon_-_Rijksmuseu](https://github.com/user-attachments/assets/278fec80-5501-4fb9-a5c1-cd604bed02af)

**Comment by DannyGJdeJong** [comment]
De Borman werkplaats is een `crm:E74_Group` en die nemen we niet mee in deze query. We moeten nog even bespreken hoe we nou precies groepen willen behandelen aangezien we elders groepen uit elkaar trekken in hun individuele leden.
