### ISSUE TITLE
Etikettekst - Omschrijving ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#33]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Etikettekst (omschrijving) in sommige gevallen niet aanwezig

## Relevant examples

Rijksstudio links:

1. Niet aanwezig: http://rijksmuseum.nl/collectie/NG-2006-110-3
2. Wel aanwezig: https://www.rijksmuseum.nl/nl/collectie/SK-A-4688

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Muts-dubbel-met-oorkleppen-en-rode-blauwgroene-zwarte-en-lichtbruine-horizontale-strepen-in-verschillende-breedten--7cebc88941bc8ef6aceae68e7e2b9295?&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Italiaans-landschap-met-parasoldennen--ebe61d8e3b3a3817793b7503ac99752b?&tab=data

---
## Screenshots

![Screenshot 2024-07-26 at 14 39 27](https://github.com/user-attachments/assets/d7b21bbc-1226-46b3-91d7-9d0cda3e1acc)

**Comment by jorisbr** [comment]
Fix voor https://rijks-acc.q42labs.com/nl/collectie/object/Italiaans-landschap-met-parasoldennen--ebe61d8e3b3a3817793b7503ac99752b?&tab=data:

**Comment by jorisbr** [comment]
De tweede case komt doordat er voor deze wall text geen creation date bestaat. De creation date wordt door ons gebruikt om te bepalen welke text de meeste huidige versie is en dat is de tekst die we willen tonen. Aangezien deze date niet bestaat komt er geen resultaat terug en hebben we in dit geval niks in de UI. 
Inmiddels zou er een preferred type terug moeten komen zie dit issue: https://github.com/Rijksmuseum/pattern_book/issues/432
Met dit preferred type kunnen we langs de label queries om deze flink te versimpelen en de kwaliteit van de output te verhogen

**Comment by jorisbr** [comment]
> Fix voor https://rijks-acc.q42labs.com/nl/collectie/object/Italiaans-landschap-met-parasoldennen--ebe61d8e3b3a3817793b7503ac99752b?&tab=data:

Deze fix moet teruggedraaid worden: https://github.com/Q42/Rijksmuseum/pull/4587

**Comment by DannyGJdeJong** [comment]
We laten nu de juiste etikettekst zien, maar daarmee verdwijnt wel de andere beschrijving. Is dit wat we willen?

Voor de wollen muts komt nu terug: 
```
In 1980 onderzochten archeologen de graven van 185 Nederlandse mannen die in de 17de eeuw op of nabij Spitsbergen overleden: walvisvaarders en arbeiders van de traankokerijen. De skeletten hadden hun mutsen nog op. Deze mutsen waren persoonsgebonden; enkel aan het gestreepte patroon van de muts kon je elkaar herkennen. Vanwege de barre kou waren de mannen zo dik ingepakt dat je alleen hun ogen zag.
```

Maar de beschrijving zien we nu niet meer terug:
```
Muts, dubbel, met oorkleppen en rode, blauwgroene, zwarte en lichtbruine horizontale strepen in verschillende breedten. De binnenmuts is ook versierd met strepen. De muts bestaat uit twee op elkaar genaaide delen, elk deel is aan de bovenkant ingeknipt en vastgenaaid. Fijn breiwerk. Gebreid in tricot-steek met vijfenveertig steken en veertig naalden per tien centimeter.
```

@verwinv moeten we hier een andere issue voor aanmaken?

**Comment by verwinv** [comment]
Nee, die etikettekst is belangrijker dan de omschrijving. Op termijn willen
we misschien nog plaats maken voor andere beschrijvingen, maar niet nu.


Op ma 11 nov 2024 om 09:59 schreef Danny de Jong ***@***.***>:

**Comment by DannyGJdeJong** [comment]
Dan werkt dit dus goed nu
