### ISSUE TITLE
depictsEvent - 'Gebeurtenis' ontbreekt bij 'Dit werk gaat over:' - 'Onderwerp'

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#34]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. Adlibveld ‘Naam Gebeurtenis’ ontbreekt; daar zou bij dit object 1x “Brand in de Amsterdamse Schouwburg (1772)” moeten staan (op de oude website is dit wél correct).  
2. Onderwerp: de gebeurtenis (Franse revolutie) wordt niet getoond. In Rijksstudio wordt dit in het groepje 'wat' getoond. 

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/RP-P-OB-208.238
2. https://www.rijksmuseum.nl/nl/collectie/RP-P-2020-4972

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Gezicht-op-de-brand-in-de-Schouwburg-te-Amsterdam-op-11-mei-1772--5d9a03bf8cf202484ce50bd6a115a901?&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Gezicht-op-de-kathedraal-van-Saint-Denis-met-verwijdering-van-de-koninklijke-grafmonumenten--c4cdde95218667757ed553c6042b3a8a?&tab=data

---
## Screenshots
![Screenshot_30_07_2024__21_05](https://github.com/user-attachments/assets/f966bc71-88e2-467b-ba8b-83592456f06b)

**Comment by jorisbr** [comment]
Deze zijn inmiddels gefikst doordat het pattern book een fix voor events heeft in de laatste release
