### ISSUE TITLE
Serienummer - Property ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#36]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. Serienr: het veld serienr. ontbreekt op de website. Het wordt in Rijksstudio wel getoond, als Serienummer: 26/29 .

## Relevant examples

Rijksstudio links:
 
1. https://www.rijksmuseum.nl/nl/collectie/RP-P-2002-584
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Doctor-Syntax-kijkt-naar-een-voorstelling-in-Covent-Garden-Theatre--d5f604b3ac8c524bc462537415c2481d?&tab=data
2.

---
## Screenshots
![Screenshot_30_07_2024__21_23](https://github.com/user-attachments/assets/f3798ebf-624d-4450-9b3a-f7924e694dc7)

**Comment by jorisbr** [comment]
Ontbreekt inderdaad geheel als property. Zou een nieuwe sparql query en een update aan de pipeline vereisen om te implementeren. Vraag is of we dit voor live gang willen realiseren

**Comment by verwinv** [comment]
Dit veld is belangrijk voor prentenmensen.
Druk x van x.
