### ISSUE TITLE
Title - Soort titel moet getoond + Voormalige titel verborgen

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#37]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

(1) We moeten het 'soort titel' tonen
(2) De titels hebben een volgorde die ze moeten aanhouden
(3) We moeten 'verworpen titels' wél tonen, maar idealiter in een uitklapper (NTH)

We maken losse kopjes van:
- PreferredTitle
- OriginalTitle
- InscribedTitle
- FormerTitle

Zie voorbeelden hieronder en meer nog in [de metadatareview-sheet](https://docs.google.com/spreadsheets/d/1PF9wVdmPcj9lSuNFtFbC-yhSpprJnIN-a94gRdvhNy8/edit?gid=187235003#gid=187235003)

1. Adlibveld ‘Titel’ en Adlibveld ‘Soort Titel’ ontbreken (op de oude website is dit wél correct).
2. Adlibveld ‘Titel’ zou wél zichtbaar moeten zijn op de website als er bij Adlibveld ‘Soort Titel’ ingevuld is dat het een “titel op object” betreft; er zouden bij dit object dus nog 2 andere titels moeten staan. Bovendien moet de inhoud van het Adlibveld ‘Soort Titel’ ook getoond worden bij deze 2 titels; daar zou bij dit object dus 2x “titel op object” moeten staan (op de oude website is dit wél correct). 
3. Het label waarin staat wat voor soort titel je ziet ontbreekt (Voormalige titel). In Adlib staan echter drie voormalige titels. Er missen er dus twee.
4. Identificatie en titel: titel staat er dubbel of zelfs drie keer. Ik zie dit bij meerdere schilderijen misgaan. 
5. Ik weet niet of het "mis" is, maar uitsluitend de recentste titel wordt getoond. Eerder hebben we het er bij meetings over gehad dat ook de "geschiedenis" van oudere titels getoond zou worden. Met daarbij ook het soort titel (voormalige titel; titel op object)
6. Adlibveld ‘Titel’ zou niet zichtbaar moeten zijn op de website als er bij Adlibveld ‘Soort Titel’ ingevuld is dat het een “voormalige titel” betreft (op de oude website is dit wél correct). 
7. "In Adlib staat: 
'Isabella'
Isabella      (voormalige titel)
Jonge vrouw met waaier  (voormalige titel)
Negerinnetje      (voormalige titel)
Indisch Type      (voormalige titel)

Op de oude website staat: 
'Isabella'

Op de nieuwe website staat: 
Isabella, Jonge vrouw met waaier, 'Isabella'

Wat gaat er mis:
1)  Op de nieuwe website worden de voormalige titels niet consequent getoond; 2 voormalige titels worden wél getoond en de andere 2 voormalige titels níet.
2)  Als er voor gekozen wordt om voormalige titels wél te tonen op de nieuwe website, dan moet de toevoeging “(voormalige titel)” achter de betreffende titels gezet worden.
3)    Als er voor gekozen wordt om voormalige titels wél te tonen op de nieuwe website, dan moet ook de volgorde van de titels juist zijn (de voormalige titels worden als eerste genoemd, terwijl deze natuurlijk als laatste genoemd zouden moeten worden)."

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BI-H-1928
2. https://www.rijksmuseum.nl/nl/collectie/RP-P-AO-25-0
3. http://rijksmuseum.nl/collectie/SK-A-4062
4. http://rijksmuseum.nl/collectie/SK-C-535
5. http://hdl.handle.net/10934/RM0001.COLLECT.4675
6. https://www.rijksmuseum.nl/nl/collectie/SK-A-2931
7. https://www.rijksmuseum.nl/nl/collectie/SK-A-2931

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--8f52d4bedd6922c99ed476599f1decc6?&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Titelprent-voor-portefeuille-25-van-de-Atlas-Ottens-Amsterdam-deel-6-seculiere-gebouwen--7bc19e07e384fbce56fbb72b7fd24ed4?&tab=data
3. https://rijks-acc.q42labs.com/nl/collectie/object/Pieter-Cnoll-Cornelia-van-Nijenrode-en-hun-dochters-De-Bataviase-opperkoopman-Pieter-Cnoll-en-zijn-gezin-Pieter-Cnoll-Cornelia-van-Nijenrode-hun-dochters-en-twee-tot-slaaf-gemaakte-bedienden--1a40b77e3e7565108760dfb20b6a55e0?&tab=data
4. https://rijks-acc.q42labs.com/nl/collectie/object/Oude-vrouw-in-gebed-bekend-als-Het-gebed-zonder-end-Oude-vrouw-in-gebed--c5fa6b87598aa1777679077a46c1db5f?&tab=data
5. https://rijks-acc.q42labs.com/nl/collectie/object/Thomas-Hees-en-zijn-bediende-Thomas-en-neven-Jan-en-Andries-Hees--e4c75eab0bc9bc60411bd4e373eb6a39?&tab=data
6. https://rijks-acc.q42labs.com/nl/collectie/object/Isabella-Isabella-Jonge-vrouw-met-waaier--ead5f623d828c7250ce5413e809b3551?&tab=data
7. https://rijks-acc.q42labs.com/nl/collectie/object/Isabella-Isabella-Jonge-vrouw-met-waaier--ead5f623d828c7250ce5413e809b3551?&tab=data

---

**Comment by DannyGJdeJong** [comment]
Inmiddels ziet het er op acc zo uit: ![Image](https://github.com/user-attachments/assets/dcd236b4-5d6c-4b9f-870e-1e3ed9f2e62d)

Met de volgorde:
- preferredTitle
- inscribedTitle
- originalTitle
- formerTitle

Als dat klopt kunnen we dit issue sluiten.

**Comment by verwinv** [comment]
@DannyGJdeJong Ziet er goed uit (al gaan ze't bij Rijks niet fijn vinden dat die laatste 2 zó zichtbaar zijn), maar ik zie wel nog wat verschillen met Rijksstudio:


1. ❓ De '[Missing title](https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--8f52d4bedd6922c99ed476599f1decc6?tab=data)' is nog titelloos. In [Rijksstudio](https://www.rijksmuseum.nl/nl/collectie/BI-H-1928) heet deze 'Jours de solitude (titel op object)'
2.  ❓ [Titelprent op portefeuille](https://rijks-acc.q42labs.com/nl/collectie/object/Titelprent-voor-portefeuille-25-van-de-Atlas-Ottens-Amsterdam-deel-6-seculiere-gebouwen--7bc19e07e384fbce56fbb72b7fd24ed4?&tab=data) heeft in [Rijksstudio](https://www.rijksmuseum.nl/nl/collectie/RP-P-AO-25-0) ook de titels:
  - Atlas van Amsterdam VIe: Deel (titel op object)
  - Verzameling van Afbeeldingen en Gezichten van de Publicque Gebouwen der Stad Amsterdam (titel op object) 
3. 👍 [Pieter Cnoll](https://rijks-acc.q42labs.com/nl/collectie/object/Pieter-Cnoll-Cornelia-van-Nijenrode-en-hun-dochters-De-Bataviase-opperkoopman-Pieter-Cnoll-en-zijn-gezin-Pieter-Cnoll-Cornelia-van-Nijenrode-hun-dochters-en-twee-tot-slaaf-gemaakte-bedienden--1a40b77e3e7565108760dfb20b6a55e0?&tab=data) ziet er helemaal top uit 
4. 👍 Bij [Oude vrouw in gebed](https://rijks-acc.q42labs.com/nl/collectie/object/Oude-vrouw-in-gebed-bekend-als-Het-gebed-zonder-end-Oude-vrouw-in-gebed--c5fa6b87598aa1777679077a46c1db5f?tab=data) zie ik nu 2x dezelfde titel, maar dat heeft ze op Rijksstudio ook

**Comment by DannyGJdeJong** [comment]
Deze laten we beide zien als "inscriptie" op acc, is dit niet hoe we het willen presenteren?

Als iets geen titel heeft, willen we dan de inscribed title als fallback gebruiken?

**Comment by verwinv** [comment]
Dat zijn goeie vragen -- die ga ik via het Pattern book aan Bas vragen.
@DannyGJdeJong  Kan jij me voor die twee voorbeelden sturen hoe deze property precies heet in het Access Model?

**Comment by DannyGJdeJong** [comment]
We queryen de inscribed titles met het volgende patroon:

```sparql
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?objectUri ?nlTitle
WHERE {
    ?objectUri rdf:type crm:E22_Human-Made_Object.
    ?objectUri crm:P1_is_identified_by ?identifier.
    ?identifier crm:P190_has_symbolic_content ?idText.

    FILTER(?idText = "BI-H-1928")

    ?objectUri crm:P1_is_identified_by ?nlAppellation.
    # Getty AAT: inscribed titles
    ?nlAppellation crm:P2_has_type <http://vocab.getty.edu/aat/300417202>.
    ?nlAppellation rdf:type crm:E33_E41_Linguistic_Appellation.
    ?nlAppellation crm:P190_has_symbolic_content ?nlTitle.
}
```

**Comment by verwinv** [comment]
https://github.com/Rijksmuseum/pattern_book/issues/641

**Comment by Nondenon** [comment]
Hej! Even voor mijn begrip, bij: BI-H-1928 zien jullie een empty string bij titel? In Adlib heeft dit object wel een titel (Jours de solitude) in het veld voor titel, dus zou gewoon op een normale manier moeten doorkomen, met 'titel op object' als soort titel. Er is niet aangegeven dat dit een voorkeurstitel is maar dat zou denk ik ook niet hoeven want er is maar 1 titel bij dit object. Ik zie dus in Adlib nu niet hoe dat object afwijkt van andere objecten, maar jullie zien dit record wel als een afwijking? Vraag me dus af waarom want dan zullen er vast wel meer objecten op deze manier afwijken?

In het geval van RP-P-AO-25-0, dat object heeft 3 titels waarbij bij geen van de drie is aangegeven wat de voorkeurstitel is. De eerste titel heeft geen qualifier, misschien dat dit een probleem oplevert?

Groetjes, Shannon (informatiespecialist bij CIA, Rijksmuseum)

**Comment by DannyGJdeJong** [comment]
Wij krijgen nu de volgende voorkeurstitels:
- `BI-H-1928` - "Jours de solitude"
- `RP-P-AO-25-0` - "Titelprent voor portefeuille 25 van de Atlas Ottens (Amsterdam, deel 6: seculiere gebouwen)"

Er is dus mogelijk iets aan onze kant fout gegaan, of aan de kant van Research Services gefixt. In de toekomst zullen deze titels in ieder geval dus weer goed doorkomen.

Ik heb nu wel een [145-tal aan werken](https://github.com/user-attachments/files/17620513/query-result.2.csv) gevonden waarvoor wij geen voorkeurstitel terugkrijgen. Ik denk alleen dat het weinig zin heeft om hier nu diep in te duiken, voor bijvoorbeeld het eerste resultaat hadden we tijdens de vorige pipeline run wél een voorkeurstitel.

**Comment by Nondenon** [comment]
In ieder geval 5 daarvan hebben sws geen titel :-P

**Comment by verwinv** [comment]
@Nondenon Kan jij samen met Bas:

1. Die 142 ontbrekende voorkeurstitels aanvinken in AdLib?
2. Bespreken hoe die 5 ontbrekende titels aan een titel kunnen komen?

Ons werk hieraan beschouw ik dan als afgerond. Veel dank voor het meekijken!

**Comment by Nondenon** [comment]
Dan heb ik toch nog een vraagje, er mogen 806883 records gepubliceerd worden, daarvan hebben maar 17441 een aangevinkte titel. Dus lijkt me niet dat het daarop stuk loopt, of wel?

**Comment by DannyGJdeJong** [comment]
> Dan heb ik toch nog een vraagje, er mogen 804272 records gepubliceerd worden, daarvan hebben maar 17441 een aangevinkte titel. Dus lijkt me niet dat het daarop stuk loopt, of wel?

Lijkt mij ook niet inderdaad. Ik heb de issue bij Research Services opnieuw geopend.

> En ik zie dat ik ook over de semantische vraag ben heen gestapt, hierboven wordt nu 'titel op object' gekoppeld aan property P190 (has symbolic content) en dat klopt ergens wel, maar ergens ook weer niet. Het mooie is dat op de website van CIDOC een record van het Rijks als voorbeeld wordt genomen waarbij je goed ziet wat er wel zou moeten staan. De 'B' die ze daar noemen bij SK-A-1601 staat in Adlib in het veld <inscription.content> (228142x gevuld). Of, en zo diep zit ik nog niet in CIDOC, moet ik de hiërarchie meewegen bij de individuele properties waardoor ze feitelijk binnen hun hiërarchie een eigen interpretatie krijgen?

Deze issue is inmiddels een beetje een rommeltje geworden, excuses. Het gaat nu in principe alleen om de 145 werken waarvan wij geen "preferred terms" doorkrijgen. Dit is iets waar Research Services logica voor heeft gemaakt om er voor te zorgen dat een werk altijd een voorkeurstitel heeft, ook als deze in Adlib niet zo is aangemerkt.

De relatie P190 is een generieke relatie die zegt dat een object een stukje tekst (symbolic content) verbonden heeft. Dit wordt heel divers gebruikt, zo kan bijvoorbeeld een `Identifier` het stukje tekst `SK-A-1601` bevatten of een `Linguistic Appellation` het stukje tekst `B`.

> Verder vroegen Bas en ik ons nog af hoe jullie de data doorkrijgen in het geval van meerdere occurences in Adlib. Daar hebben ze namelijk een specifieke volgorde en bij het voorbeeld hierboven van Isabella staan de voormalige titels in een hele andere volgorde.

Deze volgorde krijgen wij helemaal niet door.

**Comment by Nondenon** [comment]
Hej Danny! 
Dank voor de uitleg! Ik kom later nog even terug op de volgorde van de titels, want dat is een aandachtspunt. Ik ga overleggen hoe dit doorwerkt in de API, aangezien ik niet zeker weet of daar een volgorde in de occurrences wordt aangegeven.
