### ISSUE TITLE
Titel - Missing title (vanwege taallabel?)

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#38]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Deze werken hebben wel een titel, die we nu niet tonen.

## Relevant examples

Rijksstudio links:

1. http://hdl.handle.net/10934/RM0001.COLLECT.287811

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--2883a419fa90faabf1b6e7b98c79cdff?&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--957d0bf97d877d4af354d2b16a6c2e8b?&tab=data
3. https://rijks-acc.q42labs.com/nl/collectie/object/Missing-Title--7f5750109d14cc5bfeffd3326b2b07cf?&tab=data

---

**Comment by jorisbr** [comment]
Deze titles hebben inderdaad geen toegewezen titel. 
We werken met een sterk wisselend patroon voor de te tonen titel. Dit geval kunnen we meenemen in de query maar die wordt er wel een stuk complexer door wat maakt dat we mogelijk in gesprek moeten met research services hierover.
