### ISSUE TITLE
Isbn - Cancelled/invalid Isbn shown in list as valid Isbn

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#4]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Chakshudana or opening the eyes: seeing south asian art anew

## Relevant examples

Koha links:

1. https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=328062

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/publicatie/Chakshudana-or-opening-the-eyes-seeing-South-Asian-art-anew--2871a35ddab29f55fb339a28891545d9?query=Chakshudana+or+opening+the+eyes&collectionDomain=Library&page=1&sortingType=Default

---
## Screenshots

<img width="1420" alt="Screenshot 2024-06-12 at 20 52 44" src="https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/c2bb6869-4a58-447b-a130-5354e2ab5534">

**Comment by jorisbr** [comment]
Pattern book issue aangemaakt: https://github.com/Rijksmuseum/pattern_book/issues/440

**Comment by DannyGJdeJong** [comment]
Solved: https://github.com/Rijksmuseum/pattern_book/issues/440#issuecomment-2178117350
