### ISSUE TITLE
hasDimensions - Volgordelijkheid

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#40]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. De afmetingen worden altijd weergegeven als hoogte x breedte, en niet breedte x hoogte. 
2. Groepering kloppend maken

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/BK-17496
2. https://www.rijksmuseum.nl/nl/collectie/SK-A-3843
3.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Blauwe-ara--b3c64fbd259c122cdf8fa9e9a32246c2?&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-een-vrouw--ddd27578727dd8dc7f8aeccb00c1e92e?query=sk-a-3843&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
3.

---

**Comment by edwardanderson** [comment]
We had the same issue trying to stabilise a dimensions description phrase from `Dimension` nodes in unpredictable order. We addressed it with a `SELECT` sub-query: https://github.com/Rijksmuseum/rdf_transformations/blob/main/rdf_transformations/europeana_data_model/parts/queries/Extent.rq

**Comment by jorisbr** [comment]
Dit vraagt ook een aanpassing aan de sparql query die we hebben voor dimensies om rekening te houden met de sort values

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/d1e958ce-8531-4864-886e-be7802f6b4fa)
