### ISSUE TITLE
Vervaardigers, Materiaal & Techniek - Volgordelijkheid termen Adlib aanhouden

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#41]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. & 2. Vervaardigers: Veld vervaardiging: prentmaker staat als laatst vermeld terwijl dit de belangrijkste maker is. Volgorde zou overeen moeten komen met de volgorde in Adlib. De namen van vervaardigers in Adlib worden genoteerd op volgorde van belang van rol.
2. Materiaal: de termen staan niet meer op dezelfde volgorde, de volgorde heeft soms een functie, denk aan hoeveelheid of belangrijkheid
3. Techniek: idem

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/RP-P-1905-5073
2. https://www.rijksmuseum.nl/nl/collectie/NG-595
3. https://www.rijksmuseum.nl/nl/collectie/AK-RBK-1972-59-A
4. https://www.rijksmuseum.nl/nl/collectie/AK-RBK-1972-59-A

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-kapitein-Notis-Botsaris--f128c49531105c18f8f7659f4967b6a7?query=RP-P-1905-5073&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-Gaspard-de-Coligny--8cf4dcb8c4d2dd40b8152d6302eb2864?query=NG-595&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
3. https://rijks-acc.q42labs.com/nl/collectie/object/Bord-met-rotsen-bamboe-prunus-en-vogels--9ee0ad54a3fb7313f7f6c018d7fe5722?query=kakiemon&collectionDomain=Art&page=2&sortingType=Popularity&tab=data
5. https://rijks-acc.q42labs.com/nl/collectie/object/Bord-met-rotsen-bamboe-prunus-en-vogels--9ee0ad54a3fb7313f7f6c018d7fe5722?query=kakiemon&collectionDomain=Art&page=2&sortingType=Popularity&tab=data

---

**Comment by jorisbr** [comment]
De volgorde van waardes voor een gegeven property moet ook voor dimensies meegenomen worden. Volgens mij moeten we een volledige lijst maken zodat we zeker weten dat deze data ook uit de integratie laag komt

**Comment by verwinv** [comment]
> De volgorde van waardes voor een gegeven property moet ook voor dimensies meegenomen worden. Volgens mij moeten we een volledige lijst maken zodat we zeker weten dat deze data ook uit de integratie laag komt

op welke plekken moet deze moeten worden meegegeven, heb ik aangevuld in [issue #335](https://github.com/Rijksmuseum/pattern_book/issues/335#issuecomment-2311811032)
