### ISSUE TITLE
Modificaties - Niet tonen

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#42]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

1. Trineke: dit hoort bij het onderdeel conservation en staat alleen in de bestandscatalogus, niet bij de objectgegevens
2. Eddy: er is info over restauraties onder een onbegrijpelijk kopje Modificaties genaamd. Deze laatste info hoort niet op een objectpagina, dat is meer iets voor intern en voor de catalogusentry

## Relevant examples

Rijksstudio links:

1. https://www.rijksmuseum.nl/nl/collectie/SK-A-3843
2. https://www.rijksmuseum.nl/nl/zoeken/objecten?q=hendrick+van+anthonissen&p=1&ps=12&st=Objects&ii=0#/SK-A-2970,0

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Portret-van-een-vrouw--ddd27578727dd8dc7f8aeccb00c1e92e?query=sk-a-3843&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2. https://rijks-acc.q42labs.com/nl/collectie/object/Schepen-bij-Zierikzee-met-de-Zuidhavenpoort-in-de-achtergrond--a0caaf127e50723ad7ba22a33a07b047?query=Hendrick+van+Anthonissen&collectionDomain=Art&page=1&sortingType=Popularity&tab=data

---

**Comment by jorisbr** [comment]
https://github.com/Q42/Rijksmuseum/pull/4588 staat in review
