### ISSUE TITLE
[MakerFullRole] - [Missende maker namen]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#43]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

De maker mist zowel in de het resultaat model als in meerdere waarden voor het MakerFullRole veld. Het lijkt er op alsof een reeks productie events een geassocieerde maker missen.

## Relevant examples

Rijksstudio links:

1.https://www.rijksmuseum.nl/nl/collectie/RP-P-1894-A-18379
2.

Collectie Online links:

1.https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Hanger-met-sfinx--f6e14e42fcd9495b09aaf5b1ac9bea7e?query=RP-P-1894-A-18379&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2.

---
## Screenshots
![image](https://github.com/user-attachments/assets/26e14098-f6fe-458e-978f-0c940b1c3a72)

**Comment by verwinv** [comment]
@jorisbr vult aan -- deze wordt opgelost door _presenting lines_

**Comment by jorisbr** [comment]
De production presenting lines gaan deze info vervangen. Er wordt [hier](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook/pull/224) gewerkt aan het sparqlbook patroon dat gebruikt kan worden zodra het access model de juiste informatie bevat.
