### ISSUE TITLE
[Preferred Title] - [A lot of missing titles]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#44]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

We hebben nu nog ruim 50k `Missing Title` instanties. We zouden kunnen overwegen om in plaats hiervan het objectnummer als naam te gebruiken. Het bijgevoegde voorbeeld heeft overigens wel een originele titel.

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Missing-Title--de6924c2c9a98be8a73c82120d63992a?collectionDomain=Art&page=1&sortingType=Popularity&facets[0].id=7edf00c6c1a64a0c870870d3dd1d645a&tab=data
2.

---

**Comment by jorisbr** [comment]
Related: https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/issues/38

**Comment by jorisbr** [comment]
Fixed by https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook/pull/178 check after next pipeline run

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/0aca1a45-2e80-4c96-9f8f-0a625e072651)

Titels komen goed door nu! We zouden (bijna) geen missing titles meer moeten hebben
