### ISSUE TITLE
[depicts/madeIn place] - de plaats Nederland als facet/node werkt niet 

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#45]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior
Er komt een 404 terug wanneer met het nodeId van het gehucht nederland informatie opgehaald wordt.
https://rijks-acc.q42labs.com/api/v1/collection/node?nodeId=9194c8671e1e3ed04d7b67f3b3c2c601&language=nl

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2. nvt

---

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/0467294b-8d8c-4737-93ab-d1a893d55da2)

Als facet werkt het, maar er hangt inderdaad geen nodepagina aan vast. Verwachten we deze wel?
