### ISSUE TITLE
[Toont persoon] - [Data missync tussen neo4j en elastic]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#46]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior
Annemieke:
```
Soms kom ik rare dingen tegen in de filters van het zoeksysteem. Als ik binnen de node 'Toont Karel V' kijk op welke materialen ik kan filteren, kom ik bijvoorbeeld 'Ebbenhout' tegen met 5 treffers. Maar als ik dan wil filteren, vindt de website niets.
```

Als je kijkt naar de datatab komt er maar 1 materiaal terug. In elastic zitten 0 materialen en in Neo4j zijn 3 materialen terug te vinden.

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Bord-van-faience--b2fedc10759474ea1ece4cb0a16ff2a6?query=BK-NM-562&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2.

---

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/092862dd-3da6-40d1-8b57-5977f00227a0)

Er komen nu drie materialen terug.

Ook voor de combinatie Karel V + Ebbenhout komen nu 5 treffers terug.
