### ISSUE TITLE
[HasObjectType] - [Deze relatie ontbreekt voor sommige objecten]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#48]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Relevant examples

Rijksstudio links:

1.https://www.rijksmuseum.nl/nl/collectie/BK-NM-4580
2.

Collectie Online links:

1.https://rijks-acc.q42labs.com/nl/collectie/object/Paulus-op-weg-naar-Damascus--9319ad7de82addc12160d75102c3ccbe?query=bk-nm-4580&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2.
`https://id.rijksmuseum.nl/20070183`
---

**Comment by DannyGJdeJong** [comment]
Voor zover ik kan zien is deze gewoon aanwezig in de access store and queryen we deze ook gewoon goed. Ik verwacht dat een nieuwe pipeline run dit fixt.

**Comment by DannyGJdeJong** [comment]
Om een of andere reden gaat dit nog steeds niet goed. Hier gaan we naar kijken
