### ISSUE TITLE
[HasCatalogue] - [HasCatalogue is missing all round in the UI]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#49]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

This is because according to the pattern in our Sparql query no bestandscatalogi can be found.

## Relevant examples
SK-A-5005
Rijksstudio links:

1.
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Vrouw-met-brede-hoed--65521e32f254ad8131495971be3c15fd?query=SK-A-5005&collectionSearchContext=Art&page=1&sortingType=Default&tab=data
2.

---

**Comment by jorisbr** [comment]
An issue has been created to inquire about this in the pattern book: https://github.com/Rijksmuseum/pattern_book/issues/529

**Comment by DannyGJdeJong** [comment]
Should work again after a pipeline re-run. @jorisbr can you confirm?

**Comment by jorisbr** [comment]
> Should work again after a pipeline re-run. @jorisbr can you confirm?

Can confirm that we're getting proper results given version 0.9.1 of the pattern book and the following query:
```
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
prefix la: <https://linked.art/ns/terms/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?objectUri ?objectId ?propertyUri ?propertyId ?nlValue ?enValue
WHERE {
    {
        SELECT ?objectUri ?propertyUri
        WHERE {
            ?objectUri rdf:type crm:E22_Human-Made_Object.
            ?objectUri crm:P67i_is_referred_to_by ?catalogueEntry.
            # reports
            ?catalogueEntry crm:P2_has_type <http://vocab.getty.edu/aat/300027267>.
            ?catalogueEntry crm:P106i_forms_part_of ?propertyUri.
        }
        ORDER BY ?objectUri
        LIMIT 50000
        OFFSET 0
    }

    ?objectUri la:member_of ?objectSet.
    ?objectSet rdf:type la:Set. # This could possible slow down in the future
    ?objectSet crm:P1_is_identified_by ?objectSetName.
    ?objectSetName rdf:type crm:E33_E41_Linguistic_Appellation.
    ?objectSetName crm:P190_has_symbolic_content ?objectSetNameText .

    BIND(MD5(STR(?objectUri)) AS ?objectId)
    BIND(MD5(STR(?propertyUri)) AS ?propertyId)
    BIND(?objectSetNameText AS ?nlValue)
    BIND(?objectSetNameText AS ?enValue)
}

```

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/57d8bb91-5142-42f0-87db-ed7de81ddb1e)
