### ISSUE TITLE
[Fix provenance velden]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#51]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

"Herkomst"-veld als node.

## Relevant examples

To be added still

Rijksstudio links:

1.https://www.rijksmuseum.nl/nl/zoeken/objecten?q=hoed&p=1&ps=12&st=Objects&ii=0#/SK-A-5005,0
2.

Collectie Online links:

1.https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Vrouw-met-brede-hoed--65521e32f254ad8131495971be3c15fd?query=SK-A-5005&collectionSearchContext=Art&page=1&sortingType=Default&tab=data
2.

---

**Comment by DannyGJdeJong** [comment]
@jorisbr heb jij hier een patternbook voorbeeld van? Als dat er is maak ik er een ticket voor aan en ga ik er mee aan de slag

**Comment by jorisbr** [comment]
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/519835cb-a9c2-4e58-838f-1786f94a4bfd">
<img width="1141" alt="image" src="https://github.com/user-attachments/assets/96896532-260b-4d91-bb52-1641eca43723">
Zie dat hier een deel van de herkomst mist en de opmerkingen ontbreken als apart veld

**Comment by jorisbr** [comment]
> provenanceAcquisitionMethod moet provenanceAcquisition worden met [verwervingsmethode] [datum]
Dit is belangrijk om in de gaten te houden als we de pipeline modellen gaan bijwerken. Daarom maak ik vast een ticket voor het bijwerken van de pipeline modellen voor de kunstcollectie.
