### ISSUE TITLE
Type - Koha-veld 'item type' ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#55]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- Bij het **type** staat nu de  **omschrijving** (bvb.: '224 p. : ill. ; 30 cm.' -- dat komt uit MARC-veld 300 ## - PHYSICAL DESCRIPTION) 👉 👉 zie [JIRA](https://rijksmuseum.atlassian.net/browse/CO-1889)
- Onder **Type** bovenaan zou moeten staan dat het om een boek, een veilingcatalogus, een artikel, ...  gaat (MARC-veld 942 ## - ADDED ENTRY ELEMENTS (KOHA) -- Koha item type) -- dit zijn doorklikbare nodes. Deze ontbreken nu.

Dit **item type** hebben we ook nodig om in het zoekresultaat onderscheid te maken!

## Relevant examples

KOHA links:

1. Boek: https://library.rijksmuseum.nl/cgi-bin/koha/opac-MARCdetail.pl?biblionumber=194099
2. Special collections: [Reglement voor de Bataafsche gewapende burgermacht.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=234664)
3. Exhibition catalogs: [Vis : stillevens van Hollandse en Vlaamse meesters 1550-1700 / concept, samenst. en red. Liesbeth M. Helmus; auteurs Eddy de Jongh ... [et al.]](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=146170)
4. Artikel: [The horse aquamanile in the Rijksmuseum : a 'new’ Andalusian or Fatimid bronze / Joanna Olchawa.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=331253)
5. Auction catalogs: [The Sam Josefowitz collection : graphic masterpieces by Rembrandt van Rijn.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=329512)

Collectie Online links:

1. Boek: [Landhuizen in Zweden](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Landhuizen-in-Zweden--ba43afe5a1719a8b0bae7d075b18996d?query=landhuizen+in+zweden&collectionDomain=Library&page=1&sortingType=Default)
2. Special collections: [Reglement voor de Bataafsche gewapende burgermacht.](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Reglement-voor-de-Bataafsche-gewapende-burgermacht-Gearresteert-by-de-Nationale-Vergadering-representeerende-het-volk-van-Nederland-Den-13-september-1796-Het-tweede-jaar-der-Bataafsche-vryheid--08b048713afa23a97c716c54d7225213?query=nederland&collectionDomain=Library&page=1&sortingType=Default)
3. Exhibition catalogs: [Vis: stillevens van Hollandse en Vlaamse meesters 1550-1700](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=146170)
4. Artikel: [The horse aquamanile in the Rijksmuseum: a 'new’ Andalusian or Fatimid bronze](https://rijks-acc.q42labs.com/nl/collectie/publicatie/The-horse-aquamanile-in-the-Rijksmuseum-a-new-Andalusian-or-Fatimid-bronze--47f8164bb6bb9f6124d8713e67777805?query=The+horse+aquamanile+in+the+Rijksmuseum&collectionDomain=Library&page=1&sortingType=Default)
5. Auction catalogs: [The Sam Josefowitz collection: graphic masterpieces by Rembrandt van Rijn](https://rijks-acc.q42labs.com/nl/collectie/publicatie/The-Sam-Josefowitz-collection-graphic-masterpieces-by-Rembrandt-van-Rijn--ba9ac86ea74e42210a14896cdf810ca9?query=The+Sam+Josefowitz+collection+%3A+graphic+masterpieces+by+Rembrandt+van+Rijn&collectionDomain=Library&page=1&sortingType=Default)

---
## Screenshots

![MARC_details_voor_record_nr__194099_›_Rijksmuseum_Research_Library_catalogus_and_Landhuizen_in_Zweden_-_Rijksmuseum_and_rijksmuseum-coll-onl-q42__Channel__-_Eidra_-_Slack](https://github.com/user-attachments/assets/b053b8a8-3df8-4bbf-8148-803b5673c913)

**Comment by DannyGJdeJong** [comment]
Het lijkt erop dat dit item type helemaal niet in de access store zit. @jorisbr kan jij dit bevestigen en een patternbook issue aanmaken?

**Comment by verwinv** [comment]
Deze pattern book-issues zijn hieraan gerelateerd:

- https://github.com/Rijksmuseum/pattern_book/issues/229
- [Genre] https://github.com/Rijksmuseum/pattern_book/issues/441

**Comment by jorisbr** [comment]
Deze data is via de genre relatie al in zeker zin beschikbaar:
```
select * where {
    ?work ?relation ?shouldBeAUri.
    ?shouldBeAUri <http://schema.org/name> "Auction catalogs" .
    ?shouldBeAUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/DefinedTerm>.
} limit 200
```

Volgens mij dekt https://github.com/Rijksmuseum/pattern_book/issues/441 de taak om dit beschikbaar te stellen en de nodige verbeteringen. Ivo stelt de nodige vragen bij de implementatie van dit veld voor het access model. Ik neem aan dat Ivo dit zelf of eventueel samen met Edward fikst.
