### ISSUE TITLE
'Door' & 'Met medewerking van' - Auteurs / contributors ontbreken

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#56]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- Collectie Online toont geen auteurs of medewerkers

## Relevant examples

Koha links:

1. [Landhuizen in Zweden](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=194099)
2. [Vis : stillevens van Hollandse en Vlaamse meesters 1550-1700 / concept, samenst. en red. Liesbeth M. Helmus; auteurs Eddy de Jongh ... [et al.]](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=146170)
3. [The horse aquamanile in the Rijksmuseum : a 'new’ Andalusian or Fatimid bronze / Joanna Olchawa.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=331253)
4. [The horse aquamanile in the Rijksmuseum : a 'new’ Andalusian or Fatimid bronze / Joanna Olchawa.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=331253)
5. [The Sam Josefowitz collection : graphic masterpieces by Rembrandt van Rijn.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=329512)

Collectie Online links:

1. Door [Auteur] + Met medewerking van [contributors] ontbreekt: [Landhuizen in Zweden](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Landhuizen-in-Zweden--ba43afe5a1719a8b0bae7d075b18996d?query=zweden&collectionDomain=Library&page=1&sortingType=Default)
2. Auteur ontbreekt, medewerkers wel te zien: [Vis: stillevens van Hollandse en Vlaamse meesters 1550-1700](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=146170)
6. Auteur staat bij 'met medewerking van' + Contributor ontbreekt: [The horse aquamanile in the Rijksmuseum: a 'new’ Andalusian or Fatimid bronze](https://rijks-acc.q42labs.com/nl/collectie/publicatie/The-horse-aquamanile-in-the-Rijksmuseum-a-new-Andalusian-or-Fatimid-bronze--47f8164bb6bb9f6124d8713e67777805?query=The+horse+aquamanile+in+the+Rijksmuseum&collectionDomain=Library&page=1&sortingType=Default)
7. Auteur ontbreekt (geen contributors): [The Sam Josefowitz collection: graphic masterpieces by Rembrandt van Rijn](https://rijks-acc.q42labs.com/nl/collectie/publicatie/The-Sam-Josefowitz-collection-graphic-masterpieces-by-Rembrandt-van-Rijn--ba9ac86ea74e42210a14896cdf810ca9?query=The+Sam+Josefowitz+collection+%3A+graphic+masterpieces+by+Rembrandt+van+Rijn&collectionDomain=Library&page=1&sortingType=Default)

---
## Screenshots

![Landhuizen_in_Zweden_-_Rijksmuseum_and_Details_voor__Landhuizen_in_Zweden___›_Rijksmuseum_Research_Library_catalogus_and_rijksmuseum-coll-onl-q42__Channel__-_Eidra_-_Slack](https://github.com/user-attachments/assets/90adeb6c-e923-4ec8-bbb9-c9f0560b3ac1)

**Comment by DannyGJdeJong** [comment]
1. `Met medewerking van` is nu wel aanwezig. `Door` komt terug in onze hasCreator property, de query hiervoor is er al maar is nog nergens geïntegreerd.
2. `Door` komt wel terug in de hasCreator property, maar is nog niet geïntegreerd.
3. - HasCreator -> Olchawa, Joanna -> moet nog worden geïntegreerd
    - HasAuthorPerson -> Olchawa, Joanna 
    - HasContributor -> n/a
    - Rijksmuseum komt in de data alleen voor als "editor", volgens koha is het een 'col' en een 'edt', niet een contributor. We hebben geen query die de `schema:editor` relatie ophaalt en de 'col' relatie lijkt in de access store helemaal niet terug te komen.
    - Auteur staat inderdaad onder "met medewerking van", maar wel met de relatie "heeft auteur", dit is iets wat aangepast moet worden in de front- of back-end.
4. `Door` komt wel terug in de hasCreator property, maar is nog niet geïntegreerd.

Tl;dr
- HasCreator moet worden geïntegreerd.
- HasAuthorPerson (en mogelijk HasAuthorOrganisation) moeten niet onder het kopje "met medewerking van" maar onder een ander kopje komen in de front-end.
- We hebben mogelijk een `HasEditor` property nodig als hier wens naar is.

**Comment by DannyGJdeJong** [comment]
Dit is nu allemaal te zien op acc!
