### ISSUE TITLE
Uitgever - Uitgever ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#57]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- Uitgever & plaats van uitgifte ontbreken, zie voorbeelden onder
- Dit gaat zowel over de _presenting line_ als over de nodes van Uitgever

## Relevant examples

Koha links:

1. [Landhuizen in Zweden](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=194099)
2. [Vis : stillevens van Hollandse en Vlaamse meesters 1550-1700 / concept, samenst. en red. Liesbeth M. Helmus; auteurs Eddy de Jongh ... [et al.]](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=146170)
3. [The Sam Josefowitz collection : graphic masterpieces by Rembrandt van Rijn.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=329512)

Collectie Online links:

1. Publication details ontbreken: [Landhuizen in Zweden](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Landhuizen-in-Zweden--ba43afe5a1719a8b0bae7d075b18996d?query=zweden&collectionDomain=Library&page=1&sortingType=Default)
2. [Vis: stillevens van Hollandse en Vlaamse meesters 1550-1700](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Vis-stillevens-van-Hollandse-en-Vlaamse-meesters-1550-1700--100d6dc236407e66b2bf0ef013f74d6d?query=9059830040&collectionSearchContext=Library&page=1&sortingType=Default)
3. [The Sam Josefowitz collection: graphic masterpieces by Rembrandt van Rijn](https://rijks-acc.q42labs.com/nl/collectie/publicatie/The-Sam-Josefowitz-collection-graphic-masterpieces-by-Rembrandt-van-Rijn--ba9ac86ea74e42210a14896cdf810ca9?query=The+Sam+Josefowitz+collection+%3A+graphic+masterpieces+by+Rembrandt+van+Rijn&collectionDomain=Library&page=1&sortingType=Default)

---
## Screenshots

![Landhuizen_in_Zweden_-_Rijksmuseum_and_Details_voor__Landhuizen_in_Zweden___›_Rijksmuseum_Research_Library_catalogus_and_rijksmuseum-coll-onl-q42__Channel__-_Eidra_-_Slack](https://github.com/user-attachments/assets/330e4bd4-9518-4142-88ba-fed60639d742)

**Comment by DannyGJdeJong** [comment]
Deze property zit nu in Elastic, maar wordt nog niet doorgegeven aan de front-end. Ik heb hiervoor een ticket aangemaakt: https://rijksmuseum.atlassian.net/browse/CO-1916

**Comment by jorisbr** [comment]
Alle drie de voorbeelden hebben inmiddels de juiste uitgifte informatie
