### ISSUE TITLE
Onderwerp - Onderwerp ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#58]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- De onderwerpen zijn niet zichtbaar

## Relevant examples

Rijksstudio links:

1. https://rijks-acc.q42labs.com/nl/collectie/publicatie/Landhuizen-in-Zweden--ba43afe5a1719a8b0bae7d075b18996d?query=landhuizen+in+zweden&collectionDomain=Library&page=1&sortingType=Default
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/publicatie/Landhuizen-in-Zweden--ba43afe5a1719a8b0bae7d075b18996d?query=landhuizen+in+zweden&collectionDomain=Library&page=1&sortingType=Default
2.

---
## Screenshots

![Landhuizen_in_Zweden_-_Rijksmuseum_and_Details_voor__Landhuizen_in_Zweden___›_Rijksmuseum_Research_Library_catalogus_and_rijksmuseum-coll-onl-q42__Channel__-_Eidra_-_Slack](https://github.com/user-attachments/assets/d678ac34-755e-4f29-8d9e-7609f1d74459)

**Comment by DannyGJdeJong** [comment]
Is inmiddels weer te zien.
