### ISSUE TITLE
Inhoud - Inhoud ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#59]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- Inhoud is niet zichtbaar, zou dat wel moeten wezen

## Relevant examples

KOHA links:

1. [Reglement voor de Bataafsche gewapende burgermacht.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=234664)
2.

Collectie Online links:

1. [Reglement voor de Bataafsche gewapende burgermacht.](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Reglement-voor-de-Bataafsche-gewapende-burgermacht-Gearresteert-by-de-Nationale-Vergadering-representeerende-het-volk-van-Nederland-Den-13-september-1796-Het-tweede-jaar-der-Bataafsche-vryheid--08b048713afa23a97c716c54d7225213?query=nederland&collectionDomain=Library&page=1&sortingType=Default)
2.

---
## Screenshots

![Details_voor__Reglement_voor_de_Bataafsche_gewapende_burgermacht__Gearresteert_by_de_Nationale_Vergadering__representeerende_het_volk_van_Nederland__Den_13__september_1796__Het_tweede_jaar_der_Bataafsche_vryheid__›_Rijksmuseum_Research_Libr](https://github.com/user-attachments/assets/c92b7c7b-70ca-4f37-9501-82de23208be8)

**Comment by DannyGJdeJong** [comment]
Inmiddels laten we deze wel zien.
