### ISSUE TITLE
'Meer informatie' - ontbreekt gedeeltelijk

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#60]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- ' Meer informatie' bevat slechts een gedeelte van de  500 ## - GENERAL NOTE-velden

In het voorbeeld van de Bataafsche republiek:
❌  General note | Drukkersmerk
❌  General note | Lettertype romein
❌  General note | Typografische titelpagina
✅  General note | π A 4 * A-E 8 F 4 (F4 blanco)

## Relevant examples

KOHA links:

1. https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=234664
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/publicatie/Reglement-voor-de-Bataafsche-gewapende-burgermacht-Gearresteert-by-de-Nationale-vergadering-representerende-het-volk-van-Nederland-Den-13-September-1796-Het-tweede-jaar-der-Bataafsche-vryheid--bd02b76176c274825945c4f588228aa7?query=reglement+voor+de+bataafsche&collectionDomain=Library&page=1&sortingType=Default
2.

---
## Screenshots

![Details_voor__Reglement_voor_de_Bataafsche_gewapende_burgermacht__Gearresteert_by_de_Nationale_Vergadering__representeerende_het_volk_van_Nederland__Den_13__september_1796__Het_tweede_jaar_der_Bataafsche_vryheid__›_Rijksmuseum_Research_Libr](https://github.com/user-attachments/assets/007deac0-5b1e-487a-92ca-79d3f7a29554)

**Comment by DannyGJdeJong** [comment]
Zowel in GraphDB en Elastic komen alle vier de waardes gewoon door:

```
  "descriptiveNote": [
    "π A 4 * A-E 8 F 4 (F4 blanco)",
    "Drukkersmerk",
    "Lettertype romein",
    "Typografische titelpagina"
  ],
 ```

Het lijkt erop dat er ergens alleen de eerste wordt gepakt.

**Comment by DannyGJdeJong** [comment]
Je hebt hier het verkeerde koha object gelinkt.

https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=216069 is het goede koha object, deze heeft alleen `π A 4 * A-E 8 F 4 (F4 blanco)` als general note. 

Het goede bijbehorende object op acc is https://rijks-acc.q42labs.com/nl/collectie/publicatie/Reglement-voor-de-Bataafsche-gewapende-burgermacht-Gearresteert-by-de-Nationale-Vergadering-representeerende-het-volk-van-Nederland-Den-13-september-1796-Het-tweede-jaar-der-Bataafsche-vryheid--08b048713afa23a97c716c54d7225213 die wél alle vier de general notes laat zien.

**Comment by verwinv** [comment]
Ahhh, _blimey_, dat gaat dan vrees ik in meerdere issues gebeurd zijn. Scherp, thx @DannyGJdeJong.
