### ISSUE TITLE
[HasMuseumLocation] - [De museum locatie wordt niet altijd door gegeven]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#61]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Als je de link naar col online volgt zie je op 1 de nachtwacht met "te zien op" het tweede resultaat heeft "te zien in zaal 17e eeuw". Niet alle museum locatie patronen zijn correct gevat in de sparql query en dit moet dus nog geadresseerd worden.

Zaalnummers zijn ook nodig voor wayfinding.
Zaalnamen moeten overeenkomen met hoe ze in Rijksstudio heten (maar zonder de secties als "17e eeuw").
Eregalerij en Nachtwachtzaal hebben eigen namen.
Te bespreken: Liefst komt dit vanuit de research services graph.

Zie bijvoorbeeld: https://rijks-acc.q42labs.com/nl/collectie/zoeken?collectionDomain=Art&page=1&sortingType=Popularity&onlyInMuseum=true&facets[0].id=ba2dc062acd137ffeac364321b7b10df&facets[1].id=3159edbfc6b22de59dfb2522fecc2706&facets[1].nodeRelationType=HasObjectType

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/zoeken?query=sk-c-5&collectionDomain=Art&page=1&sortingType=Popularity
2.

---

**Comment by DannyGJdeJong** [comment]
De Nachtwacht heeft alleen als locatie `HG-2.31` en niet iets als een zaal. Willen we dan dit laten zien?

**Comment by SandervWickeren** [comment]
@DannyGJdeJong Deze mapping gebeurde altijd aan onze kant en kunnen we misschien zien als een verreiking https://github.com/Q42/Rijksmuseum/blob/102530254c978e47417b4315ede5675a2edd3efd/src/Rijksmuseum.Domain/Collection/HnrCode.cs#L257. Laat de eerste stap vooral zijn dat `HG-2.31` zichtbaar wordt. Daarna kunnen we verder kijken.

> Ik merk ook dat veel werken "te zien in zaal" erbij hebben en vervolgens helemaal geen crm:P55_has_current_location relatie hebben in de access store. Op wat baseren we nu dat een werk in het museum hangt?

Dit is gefixed in https://github.com/Q42/Rijksmuseum/pull/4786, ik heb jou geassigned als reviewer :)

**Comment by DannyGJdeJong** [comment]
Fixed in https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook/pull/181 en https://github.com/Q42/Rijksmuseum/pull/4798

**Comment by verwinv** [comment]
@DannyGJdeJong Zitten hier nu ook de correcte "[exhibition building spaces](http://vocab.getty.edu/aat/300260522)"-benamingen bij, of maak ik beter een apart issue aan om deze door te laten komen?

**Comment by jorisbr** [comment]
> @DannyGJdeJong Zitten hier nu ook de correcte "[exhibition building spaces](http://vocab.getty.edu/aat/300260522)"-benamingen bij, of maak ik beter een apart issue aan om deze door te laten komen?

In de huidige PR zitten die er nog niet bij maar dat voeg ik toe als requirement. Dit is makkelijker om in 1 keer te fiksen

**Comment by DannyGJdeJong** [comment]
We hebben nu hasMuseumLocation en hasMuseumLocationHall geïmplementeerd. Zo kunnen we zowel de locatiecode als de zaal laten zien in de front-end.

**Comment by DannyGJdeJong** [comment]
De museumlocatie wordt nu altijd meegegeven. We laten in het zoekoverzicht alleen de locatiecode zien en we gebruiken de zaalnamen nu nergens.
