### ISSUE TITLE
Item type - Type (afk.) komt door als genre

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#62]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- Onder 'Genre' zijn afkortingen als 'AUC' (auction catalogue), 'ART' (article), 'EXH' (exhibition catalog), 'SPEC. COLL' (special collections), 'BKS' (books) nog te zien. Deze item type afkorting moet uit het veld 'genre'.

Hier is een Pattern book issue van: https://github.com/Rijksmuseum/pattern_book/issues/441

## Relevant examples

Koha links:

1. [Reglement voor de Bataafsche gewapende burgermacht.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=234664)
2. [Landhuizen in Zweden](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=194099)
3. [Vis : stillevens van Hollandse en Vlaamse meesters 1550-1700 / concept, samenst. en red. Liesbeth M. Helmus; auteurs Eddy de Jongh ... [et al.]](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=146170)
4. [The horse aquamanile in the Rijksmuseum : a 'new’ Andalusian or Fatimid bronze / Joanna Olchawa.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=331253)
5. AUC: [The Sam Josefowitz collection : graphic masterpieces by Rembrandt van Rijn.](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=329512)

Collectie Online links:

1. SPEC. COLL: [Reglement voor de Bataafsche gewapende burgermacht.](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Reglement-voor-de-Bataafsche-gewapende-burgermacht-Gearresteert-by-de-Nationale-Vergadering-representeerende-het-volk-van-Nederland-Den-13-september-1796-Het-tweede-jaar-der-Bataafsche-vryheid--08b048713afa23a97c716c54d7225213?query=nederland&collectionDomain=Library&page=1&sortingType=Default)
2. BKS: [Landhuizen in Zweden](https://rijks-acc.q42labs.com/nl/collectie/publicatie/Landhuizen-in-Zweden--ba43afe5a1719a8b0bae7d075b18996d?query=zweden&collectionDomain=Library&page=1&sortingType=Default)
6. EXH: [Vis: stillevens van Hollandse en Vlaamse meesters 1550-1700](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=146170)
7. ART: [The horse aquamanile in the Rijksmuseum: a 'new’ Andalusian or Fatimid bronze](https://rijks-acc.q42labs.com/nl/collectie/publicatie/The-horse-aquamanile-in-the-Rijksmuseum-a-new-Andalusian-or-Fatimid-bronze--47f8164bb6bb9f6124d8713e67777805?query=The+horse+aquamanile+in+the+Rijksmuseum&collectionDomain=Library&page=1&sortingType=Default)
8. AUC: [The Sam Josefowitz collection: graphic masterpieces by Rembrandt van Rijn](https://rijks-acc.q42labs.com/nl/collectie/publicatie/The-Sam-Josefowitz-collection-graphic-masterpieces-by-Rembrandt-van-Rijn--ba9ac86ea74e42210a14896cdf810ca9?query=The+Sam+Josefowitz+collection+%3A+graphic+masterpieces+by+Rembrandt+van+Rijn&collectionDomain=Library&page=1&sortingType=Default)

---

**Comment by jorisbr** [comment]
Wordt gefikst in [deze PR](https://github.com/Q42/Rijksmuseum/pull/4830)
