### ISSUE TITLE
Onderwerp - Komt niet door op gegevens-tab

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#63]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Onderwerpen als 'Historiestuk' en 'Sociale geschiedenis' komen wel door als node (met nodepagina's) maar zijn niet zichtbaar als onderwerp op de Gegevens-tab.

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1. Check de kunstwerken gelinkt aan [historiestuk](https://rijks-acc.q42labs.com/nl/collectie/node/historiestuk--7f3cae779efc72d495a8c384816a7363)
2. idem voor [sociale geschiedenis](https://rijks-acc.q42labs.com/nl/collectie/node/sociale-geschiedenis--534d080345c4b7bbbe536ebf13f881d5)

---

**Comment by DannyGJdeJong** [comment]
Het lijkt erop dat HasSubject relaties niet doorkomen in de API ook al staan deze wél gewoon in Elastic en komen ze ook door in de Neo4j query. Er gaat dus ergens iets mis in de mapper.

Ik heb er een issue voor aangemaakt: https://rijksmuseum.atlassian.net/browse/CO-1941

**Comment by jorisbr** [comment]
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/fd3fa80f-2457-4ee5-a682-fff2d941661e">
Fixed!
