### ISSUE TITLE
Groepen - Groepen worden niet als maker aangemerkt

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#65]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Op dit moment ontbreken werken die "toegeschreven aan" zijn maar wel een primary maker relatie hebben met deze persoon. 

Check nodepagina Geertgen tot Sint Jans: SK-A-3901

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/node/Geertgen-tot-Sint-Jans--06a3d96a4785ce67aa8e551741dd763d?collectionSearchContext=Art&page=1&sortingType=Popularity&facets[0].id=06a3d96a4785ce67aa8e551741dd763d
2.

---

**Comment by jorisbr** [comment]
Dit is een lastige situatie. Wat blijkt is dat we 1 instantie hebben van Geertgen als zijnde een persoon en de andere twee werken zijn uitgevoerd door een groep. Ik ga kijken in hoeverre we dit kunnen consolideren

**Comment by DannyGJdeJong** [comment]
Dit is nu, als het goed is, meegenomen in alle queries
