### ISSUE TITLE
Fallback - Engelstalige term niet beschikbaar

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#68]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

De Engelstalige term van 'Tweede Wereldoorlog', 'Tachtigjarige Oorlog', 'Honderdjarige Oorlog' wordt niet getoond - we tonen ook geen _fallback_-term of [Missing Title], enkel een lege node.

- Voor ‘Meester van het Amsterdamse Kabinet’ is in Neo4j-prod de EN value gelijk aan NL
- Voor “feest” is er in Neo4j-prod géén EN value
- voor “boekband (ontwerp)” is er in Neo4j-prod géén EN value
- voor “Tachtigjarige Oorlog” is er in Neo4j-prod géén EN value
- van “Tweede Wereldoorlog” hebben we twee verschillende Nodes in het Access Model, waarvan er één wel, één niet een Engelse waarde meekrijgt

Bron: https://q42.slack.com/archives/C0787EPL9TR/p1727865902357819

## Relevant examples

Rijksstudio links:

1. 
2.

Collectie Online links:

1. https://www.rijksmuseum.nl/nl/collectie/node/Tachtigjarige-Oorlog--48df629bd498ec1a62faa562776a82fe?collectionSearchContext=Art&page=1&sortingType=Popularity&facets[0].id=48df629bd498ec1a62faa562776a82fe
2.

---
## Screenshots

![Screenshot 2024-10-08 at 14 00 13](https://github.com/user-attachments/assets/b358d041-7134-43df-8622-e19c6f8a3494)

**Comment by verwinv** [comment]
Check nadat https://rijksmuseum.atlassian.net/browse/CO-975 is doorgevoerd

**Comment by DannyGJdeJong** [comment]
> De Engelstalige term van 'Tweede Wereldoorlog', 'Tachtigjarige Oorlog', 'Honderdjarige Oorlog' wordt niet getoond - we tonen ook geen fallback-term of [Missing Title], enkel een lege node.

Om een of andere reden zijn deze termen in Neo4j en Elastic niet doorgekomen. In de queries worden deze gewoon teruggegeven dus ik verwacht dat het na een pipeline-run gewoon weer werkt.

> Voor ‘Meester van het Amsterdamse Kabinet’ is in Neo4j-prod de EN value gelijk aan NL
Klopt, er is voor Meester van het Amsterdamse Kabinet geen Engelse waarde in de access store. Verwachten we dat die er wel is?

> Voor “feest” is er in Neo4j-prod géén EN value
voor “boekband (ontwerp)” is er in Neo4j-prod géén EN value
voor “Tachtigjarige Oorlog” is er in Neo4j-prod géén EN value

Zelfde als het eerste punt. Moeten we checken na een re-run.

> van “Tweede Wereldoorlog” hebben we twee verschillende Nodes in het Access Model, waarvan er één wel, één niet een Engelse waarde meekrijgt
De ene is een term die wordt gebruikt in de bibliotheekdata (`schema:DefinedTerm`) terwijl de ander wordt gebruikt in de kunstdata (`crm:E7_Activity`). Alleen die laatste heeft alleen een Nederlandse term om onbekende reden. Dit moeten we opnieuw checken na een re-run. @jorisbr moeten we deze termen reconcilen?

**Comment by DannyGJdeJong** [comment]
Alle punten zijn nu opgelost 🥳
