### ISSUE TITLE
Nodepagina - Door de tijd-blok niet gegenereerd

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#69]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- Maker-rol [Pottenbakker](https://rijks-acc.q42labs.com/nl/collectie/node/pottenbakker--815090c4de4e5840b46c8ffe991272e1?collectionDomain=Art&page=1&sortingType=Popularity&facets[0].id=815090c4de4e5840b46c8ffe991272e1&facets[0].nodeRelationType=HasMakerRole) heeft 5140 gekoppelde kunstwerken (volgens zowel de data-tab als de Gegenereerde Nodepagina Editor), maar geen "Door de tijd heen"-blok

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/node/pottenbakker--815090c4de4e5840b46c8ffe991272e1?collectionDomain=Art&page=1&sortingType=Popularity&facets[0].id=815090c4de4e5840b46c8ffe991272e1&facets[0].nodeRelationType=HasMakerRole
2.

---
## Screenshots

![Screenshot 2024-10-08 at 16 20 48](https://github.com/user-attachments/assets/9d15c80c-570a-45c2-9479-170b279e456c)

**Comment by DannyGJdeJong** [comment]
Na _heel_ veel zoeken ben ik er achter. Potten worden voornamelijk gemaakt door niet-personen (anoniem/actor), en we queryen voor het genereren van de nodepaginas voor MakerRole alleen werken die een relatie met een persoon als primary maker hebben (zie https://github.com/Q42/Rijksmuseum/blob/fb278c50f30c985a654bf80dd8a619faf5c944bc/src/Rijksmuseum.Col.Services.Neo4J/Models/GeneratedPages/NodePages/NodePageTemplates.cs#L406-L429) 

Dit is blijkbaar ooit zo bedacht, maar is dit dan nog wenselijk? @verwinv @jorisbr
