### ISSUE TITLE
Library Maker - Not being recommended

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#70]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Library makers komen momenteel niet terug in de aanbevelingen-pop-up-balk, enkel onderwerpen en bibliotheekobjecten.

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2.

---

**Comment by jorisbr** [comment]
Gefikst door het recente werk aan de bibliotheekdata.
![image](https://github.com/user-attachments/assets/8e19fc56-273c-4c5f-b980-dba2cc3bc0ab)
![image](https://github.com/user-attachments/assets/c16f1d86-0d46-4721-9fa1-c952093ce8b0)
