### ISSUE TITLE
Gerelateerde werken - "gerelateerde kunstwerken"-tab ontbreekt

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#71]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Het werk "[Banda-eilanden](https://rijks-acc.q42labs.com/nl/collectie/object/Banda-eilanden--ae20ae7b6484413e5a2fcf80b5cf29bd?tab=data)" is onderdeel van een album met 14 werken. Deze staan gelinkt op de gegevens-tab, maar het object heeft geen "gerelateerde kunstwerken"-tab

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1. https://rijks-acc.q42labs.com/nl/collectie/object/Banda-eilanden--ae20ae7b6484413e5a2fcf80b5cf29bd?tab=data
2.

---
## Screenshots

![Screenshot 2024-10-08 at 18 33 19](https://github.com/user-attachments/assets/3d9055b3-63fd-4074-9f21-ec48b3cc5ab3)

**Comment by DannyGJdeJong** [comment]
De gerelateerde-kunstwerken tab is inmiddels te zien, maar werkt nog niet. Zie #72 daarvoor.
