### ISSUE TITLE
Host Item Entry - tonen

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#77]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

- **In**: cruciaal om (voor [een artikel](https://library.rijksmuseum.nl/cgi-bin/koha/opac-detail.pl?biblionumber=331253)) ook de 773 0# - HOST ITEM ENTRY op te nemen?
	- Artikelen: op dit moment is niet zichtbaar dat het om een artikel gaat. 
	- Deze informatie staat het volledigst in tag 773. Dus graag wel opnemen.
	- [ ] Currently pointed at with a URI - to implement in interface
	- [ ] Same goes for pagination information - to implement in interface (partOf)

https://github.com/Rijksmuseum/pattern_book/issues/581

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2.

---

**Comment by DannyGJdeJong** [comment]
Deze informatie hebben we nu als volgt in de front-end (moet nog gemerged worden):

<img width="457" alt="image" src="https://github.com/user-attachments/assets/d3ddcd45-af56-41cf-acd0-b414c8ed82b7">

Is dit voldoende of willen we de extra informatie (paginering) erbij?

**Comment by DannyGJdeJong** [comment]
We krijgen het jaartaal / volume / issue én paginering als 1 geheel door, e.g. "72 (2024), p. 5-22" in jouw voorbeeld, als `schema:pagination`. Dit nemen we mee in de aankomende pipeline run.

**Comment by DannyGJdeJong** [comment]
![Image](https://github.com/user-attachments/assets/554777c3-bc2d-4de5-9ebf-7d36c6424b30)
