### ISSUE TITLE
Other title - make available

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#79]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

See https://github.com/Rijksmuseum/pattern_book/issues/624

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2.

---

**Comment by jorisbr** [comment]
@verwinv Dit is er eentje voor na livegang right?
