### ISSUE TITLE
Vervaardigers - Ontbreken als node

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#8]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

(Gemeld door Annemieke in **_#rijksmuseum-invoer-pub_**) Vervaardigers als **'t Binnenhuis** of **N.V. haagsche  plateelfabriek Rozenburg** komen wel terug in de tekst, maar niet als node.

## Relevant examples

Rijksstudio links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Servies-bestaande-uit-een-theepot-melkkan-en-een-suikerpot--abba2f07478904a02293196d208f8fdb?query=BK-1969-108&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2.

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Servies-bestaande-uit-een-theepot-melkkan-en-een-suikerpot--abba2f07478904a02293196d208f8fdb?query=BK-1969-108&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Uitnodiging-voor-de-opening-van-het-tweede-tentoonstellingsgebouw-van-Atelier-voor-Woninginrichting-t-Binnenhuis--d144716b696f375d8afe6edcfd30827b?collectionDomain=Art&page=1&sortingType=Popularity&tab=data

---
## Screenshots

![Screenshot 2024-06-24 at 16 00 17](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/5059094f-9386-42b0-9963-abe35dfbc330)
![Screenshot 2024-06-24 at 15 55 51](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/986abfeb-3ae1-4dd4-88cd-073fc54c32e8)

**Comment by jorisbr** [comment]
Dit geldt voor meer dan alleen makers. Enkel de object -> object relaties komen nu door. Wordt hier gefikst: https://rijksmuseum.atlassian.net/browse/CO-1444

**Comment by jorisbr** [comment]
De deployment van de fix is onderweg

**Comment by verwinv** [comment]
Duplicates Issue #16
