### ISSUE TITLE
Makers -There are some instances of missing makers

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#85]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

The pattern we're missing for involved and primary maker is as follows:
```
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
select * where {
    ?s crm:P108i_was_produced_by ?prod .
    ?prod crm:P141i_was_assigned_by ?ass.
    ?ass crm:P141_assigned ?c.
#    ?ass crm:P177_assigned_property_of_type crm:P14_carried_out_by.
    ?c crm:P14_carried_out_by ?id.
#    filter(?s=<https://id.rijksmuseum.nl/200146319>)
#    filter(?s=<https://id.rijksmuseum.nl/200146345>)
    filter(?s=<https://id.rijksmuseum.nl/200144955>)
} limit 100
```

## Relevant examples
https://q42.slack.com/archives/C0787EPL9TR/p1731315294697739?thread_ts=1731265039.717079&cid=C0787EPL9TR

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2.

---

**Comment by DannyGJdeJong** [comment]
Komt nu goed door!
