### ISSUE TITLE
Gerelateerd object - Node-link geeft 'geen resultaten'

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#9]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Onder 'gerelateerd' op de objectdatatab staat een verwijzing naar een gerelateerd werk.
Als ik daar op doorklik, kom ik op een 404-pagina

## Relevant examples

Rijksstudio links:

#N/A

Collectie Online links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/object/Stilleven-met-bloemen-op-een-marmeren-tafelblad--570d1419506e38cb3916f640fe5a2328?query=europa&collectionDomain=Art&page=1&sortingType=Popularity&tab=data
2.

---
## Screenshots

![Screenshot 2024-06-25 at 08 47 29](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/assets/6201005/2da2e00b-24ef-4b54-aba0-95fecc53085c)

**Comment by jorisbr** [comment]
Dit wordt opgepakt door de frontend middels het volgende ticket: https://rijksmuseum.atlassian.net/browse/CO-1449
