### ISSUE TITLE
[Add rejected maker] - [Rejected maker is missing]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#90]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior
Nog niet geimplementeerd.
https://q42.slack.com/archives/C0787EPL9TR/p1731328005200369

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2.

---

**Comment by DannyGJdeJong** [comment]
Komt nu goed door!
