### ISSUE TITLE
[hasPrimaryMaker] - [In sommige gevallen ontbreekt de primary maker relatie]

### ISSUE THREAD

**Issue by jorisbr** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#91]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior
We zien de relatie in Neo4j terugkomen maar niet in Elastic. Dit heeft te maken met een een fout in de Elastic indexer waar er van uitgegaan wordt dat er altijd maar 1 primary maker is.
## Relevant examples

Rijksstudio links:

1. https://green-island-0d247b903.2.azurestaticapps.net/nl/collectie/node/Renier-van-Thienen-I--3e3dabe1f95482e237dcb4f7254854c5?collectionSearchContext=Art&page=1&sortingType=Popularity&facets[0].id=3e3dabe1f95482e237dcb4f7254854c5&facets[0].nodeRelationType=HasPrimaryMaker
2.

Collectie Online links:

1.
2.

---

**Comment by DannyGJdeJong** [comment]
Werkt, ook op productie.
