### ISSUE TITLE
[Na livegang] Persoonsnamen - Jaartallen staan nog middenin de naam

### ISSUE THREAD

**Issue by verwinv** [Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking#97]
The currently implemented properties can be found [here](https://github.com/Q42/Rijksmuseum.CollectieOnline.SparqlBook.Issue.Tracking/blob/main/properties.md).

## Describe the bug and/or desired behavior

Zie screenshot

## Relevant examples

Rijksstudio links:

1.
2.

Collectie Online links:

1.
2.

---
## Screenshots

<img width="317" alt="Screenshot 2024-11-15 at 21 14 42" src="https://github.com/user-attachments/assets/c02bcb96-8307-4ede-9d22-63a0720a6df7">

**Comment by DannyGJdeJong** [comment]
Zijn hier nog andere voorbeelden van? Dit komt nu correct door op prod
